### ISSUE TITLE
Copy-DbaLogin bug

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1541]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## Details
semi addressed in #1540

````
WARNING: [Copy-Login][22:13:29] BASE\sqlserver is the destination service account. Skipping drop.
SourceServer      : sql2014
DestinationServer : sql2016
SourceLogin       : BASE\sqlserver
DestinationLogin  : BASE\sqlserver
Type              : WindowsUser
Status            : Skipped
Notes             : Destination service account
DateTime          : 2017-07-02 22:13:29.862

SourceServer      : sql2014
DestinationServer : sql2016
SourceLogin       : dbcollectionlogin
DestinationLogin  : dbcollectionlogin
Type              : SqlLogin
Status            : Failed
Notes             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "1" argument(s): "An exception occurred while executing a
                    Transact-SQL statement or batch." ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL
                    statement or batch. ---> System.Data.SqlClient.SqlException: Supplied parameter sid is in use.
                       at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean
                    catchException)
                       at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
                       --- End of inner exception stack trace ---
                       at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
                       at CallSite.Target(Closure , CallSite , Object , Object )
                       --- End of inner exception stack trace ---
                       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                       at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
DateTime          : 2017-07-02 22:13:29.875

WARNING: [Copy-Login][22:13:29] Failed to add dbcollectionlogin to SQL2016 | Exception calling "ExecuteNonQuery" with "1" argument(s): "An exception occurred while executing a
Transact-SQL statement or batch."
SourceServer      : sql2014
````

**Comment by wsmelton** [comment]
@potatoqualitee  This is fixed by #1540 unless you still get the error even after that logic was added?

I also don't know that we want to kill EVERY process tied by that login just simply supplying the -Force parameter. It would be to easy for folks to have accidents in production :)

**Comment by potatoqualitee** [comment]
Yeah i still get the error - i also wanted some more eyes and fixes - i sorta just replaced code that was giving errors ;)

**Comment by potatoqualitee** [comment]
that only happens with -Force no?

**Comment by wsmelton** [comment]
Yeah, Force is going to drop the login but if the login has active sessions (sleeping or otherwise) you cannot drop them.

I would think this would be as design. I'm not sure I would want to see this include additional logic on dropping any session in use. I think it is catching what it should.

I will see if I can clean up the notes to just include the error message and not the full stack.

**Comment by wsmelton** [comment]
Adjusted per discussion on Slack channel. Added `KillActiveConnection` parameter to handle connections on destination.

![image](https://user-images.githubusercontent.com/11204251/27802934-86b87d22-5fec-11e7-92ac-9ab7c799b342.png)

**Comment by potatoqualitee** [comment]
sweet AF
