### ISSUE TITLE
Copy-SqlLogin & AlwaysOn permissions 

### ISSUE THREAD

**Issue by timw-be** [sqlcollaborative/dbatools#201]
More of a feature request than a issue report:

I'm using Copy-SqlLogin as a scheduled task to synchronize logins between Availability Group replica's with success, but the Function also tries to grant permissions on the synchronised user databases on the secondary replica's, which fails because the databases are not accessible on secondary replica's.

Our log contains following errors:
_15/09/2016 21:00:46
System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "1" argument(s): "ExecuteNonQuery failed for Database 'ReportServer'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: ExecuteNonQuery failed for Database 'ReportServer'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: The target database, 'ReportServer', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQuery(StringCollection queries, ExecutionTypes executionType)
   at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)_

These errors are expected as the databases are part of an Availability Group and are inaccessible on the secondary replica's.
Since database permissions are handled via the AlwaysOn sync mechanism for every database in the Availability Group, I only need the function to  add or remove SQL logins, to prevent login issues when failing over to another AG replica. Permissions and users are contained in the user database itself and are synced via the AlwaysOn sync mechanism.

Is it possible to add a switch like "-alwaysonsync" to just copy SQL logins without trying to grant db permissions on the synchronised (and inaccessible) databases? This would leave us with a cleaner exceptions log file, which is currently filled with exceptions due to inaccessible databases.

**Comment by timw-be** [comment]
Just noticed that my schedule task also included the Sync-SqlLoginPermissions Function, which caused the errors to fill the execution log. Everything runs fine after removing the Sync-SqlLoginPermissions function in my script.
You can ignore this issue.
