### ISSUE TITLE
Install-DbaFirstResponderKit fails on newest release of frk

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbatools#3328]
## Bug Report
Install-DbaFirstResponderKit now fails to install or update. 
Error: The request was aborted: Could not create SSL/TLS secure channel.

**Comment by potatoqualitee** [comment]
Oh gosh, what is going on there? I get it too.

**Comment by potatoqualitee** [comment]
Yet i can download with Chrome

**Comment by potatoqualitee** [comment]
![image](https://user-images.githubusercontent.com/8278033/36858672-03c13370-1d7c-11e8-92e6-a75c848c33d9.png)

`Invoke-WebRequest` on the url fails as well out of the box

**Comment by niphlod** [comment]
give [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 a try

**Comment by js0505** [comment]
Yep, that works. Just updated the 2 lines on the install file, force import and it is executing fine.

**Comment by js0505** [comment]
syncing up with dev and will be submitting a PR as soon as I can.

**Comment by potatoqualitee** [comment]
Consider https://codeload.github.com/ prefix instead of changing settings?

**Comment by potatoqualitee** [comment]
found it! this works: https://codeload.github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/zip/master

**Comment by js0505** [comment]
Created PR with only that one change as it works perfectly.  Thank you!

**Comment by js0505** [comment]
PR #3329

**Comment by wsmelton** [comment]
This still fails on latest release of module, 0.9.301.

```
PS C:\WINDOWS\system32> Install-DbaFirstResponderKit -SqlInstance localhost -Database NewDatabase
WARNING: [Install-DbaFirstResponderKit][03:56:37] Couldn't download the First Responder Kit. Download and install manually from
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/archive/master.zip. | The remote server returned an error: (400) Bad Request.
```

```
PS C:\WINDOWS\system32> $Error[0] | select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The
                        remote server returned an error: (400) Bad Request.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                           --- End of inner exception stack trace ---
TargetObject          :
CategoryInfo          : InvalidOperation: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Install-DbaFirstResponderKit,Stop-Function
ErrorDetails          : The remote server returned an error: (400) Bad Request.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.301\allcommands.ps1: line 88913
                        at Install-DbaFirstResponderKit<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\0.9.301\allcommands.ps1: line 43471
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```
