### ISSUE TITLE
Get-DbaXESessionTemplate - Object Reference not set...

### ISSUE THREAD

**Issue by JimPeabbles** [sqlcollaborative/dbatools#3371]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [**Works when starting powershell via cmd line using this command, Fails in PS ISE.  PSedit $PROFILE is empty.** ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): **Windows 7**
 - PowerShell Version: **5.0.10586.117**
 - SQL Server (Edition|Version): **SQL 2016 developer edition**

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Get-DbaXESessionTemplate | Out-GridView**

### Problem to solve
**Get-DbaXESessionTemplate | Out-GridView : Object reference not set to an instance of an object.
    + CategoryInfo          : NotSpecified: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException**

**Comment by potatoqualitee** [comment]
Hey Jim, thanks for your report! I tried to replicate your issue (well, i tried on 5.1 and 3.0). Can you please send the results of `$error[0] | select *` after running that command again?

**Comment by JimPeabbles** [comment]
`$error[0] | select * 


ErrorRecord                 : Object reference not set to an instance of an object.
StackTrace                  :    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable 
                              errorResults, Boolean enumerate)
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
WasThrownFromThrowStatement : False
Message                     : Object reference not set to an instance of an object.
Data                        : {}
InnerException              : System.NullReferenceException: Object reference not set to an instance of an object.
                                 at System.Management.Automation.Host.PSHostUserInterface.TranscribeCommandComplete(InvocationInfo invocation)
                                 at System.Management.Automation.Host.PSHostUserInterface.TranscribeError(ExecutionContext context, InvocationInfo 
                              invocation, PSObject errorWrap)
                                 at System.Management.Automation.ExceptionHandlingOps.ReportErrorRecord(IScriptExtent extent, RuntimeException rte, 
                              ExecutionContext context)
                                 at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object 
                              inputToProcess)
TargetSite                  : System.Array SynchronousExecuteEnumerate(System.Object, System.Collections.Hashtable, Boolean)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087 
`

**Comment by potatoqualitee** [comment]
@FriedrichWeinmann would you have any idea? I'm at a total loss.

**Comment by FriedrichWeinmann** [comment]
Well ... I can't reproduce the issue on my machine, but I've got a win10 with 5.1, he's using ISE on a win7 5.0 system. Might be a bug within ISE, might be an issue with dbatools on 5.0.
Do we have a W6.1/P5.0 machine?

**Comment by JimPeabbles** [comment]
Upgraded to PS 5.1.14409.1005 and that fixed it.  Thanks for taking a look at this.

**Comment by potatoqualitee** [comment]
Excellent news, thank you @JimPeabbles and @FriedrichWeinmann !
