### ISSUE TITLE
Backup-DbaDbCertificate 'Could not load BatchParser'

### ISSUE THREAD

**Issue by EnjoyinMoss** [sqlcollaborative/dbatools#4083]
## Steps to Reproduce

```powershell
<#
    $abc = ConvertTo-SecureString -String "mY5tr0nGP4$$w0rd!" -AsPlainText -Force
    $def = ConvertTo-SecureString -String "mY5tr0nGP4$$w0rd!" -AsPlainText -Force
    Backup-DbaDbCertificate -Database master -SqlInstance xxxx-xxxx-xxx -Path C:\ -EncryptionPassword  $abc -DecryptionPassword $def -Verbose
#>
```

## Actual Behavior

 
                        System.Management.Automation.MethodInvocationException: Exception calling "Export" with "4" argument(s): "Export failed for Certificate 
                        'tdeCert'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Export failed for Certificate 'tdeCert'.  ---> 
                        Microsoft.SqlServer.Management.Smo.FailedOperationException: ExecuteNonQuery failed for Database 'master'.  ---> 
                        System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll' or one of its dependencies. The specified 
                        module could not be found.
                           at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, 
                        ObjectHandleOnStack type)
                           at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.GetStatements(String query, ExecutionTypes executionType, Int32& 
                        statementsToReverse)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean 
                        retry)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQuery(StringCollection queries, ExecutionTypes executionType)
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
                           at Microsoft.SqlServer.Management.Smo.Certificate.Export(String certificatePath, String privateKeyPath, String encryptionPassword, String 
                        decryptionPassword)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Certificate.Export(String certificatePath, String privateKeyPath, String encryptionPassword, String 
                        decryptionPassword)
                           at CallSite.Target(Closure , CallSite , Object , Object , Object , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          : [tdeCert]
CategoryInfo          : NotSpecified: ([tdeCert]:Certificate) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_export-cert,Stop-Function
ErrorDetails          : Exception calling "Export" with "4" argument(s): "Export failed for Certificate 'tdeCert'. "
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.443\allcommands.ps1: line 99217
                        at export-cert, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.443\allcommands.ps1: line 1342
                        at Backup-DbaDbCertificate<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.443\allcommands.ps1: line 1388
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

-->

## Environmental data

x64

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.14409.1012                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.14409.1012                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by niphlod** [comment]
let's follow #4073 down the rabbit hole. Once, and for this one too.

**Comment by potatoqualitee** [comment]
Please follow #4073 - I'll close this one for now

**Comment by potatoqualitee** [comment]
Please try with version 0.9.811, released today. It uses SSMS 2018's SMO 👍
