### ISSUE TITLE
Get-DbaPermission fails on contained databases

### ISSUE THREAD

**Issue by mattbathje** [sqlcollaborative/dbatools#5093]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)
- [ ] If issue is with `Copy-DbaDatabase`, using `Backup-DbaDatabase | Restore-DbaDatabase` still does not work

Note that we do not have the resources to make `Copy-DbaDatabase` work in every environment. Instead, we try to ensure Backup & Restore work in your enviornment.

## Steps to Reproduce

1. Using SQL Server 2016 with Contained Databases, databases have collation type Latin1_General_100_CI_AS
2. Run command get-dbapermission -server instance

```powershell
get-dbapermission -server instance 
```

## Expected Behavior

Return the proper list of permissions, including database-level permissions for all databases. 

## Actual Behavior

When getting database level permissions for any contained databases, an error is returned:

```
Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'DBTest1'. "
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:43772 char:17
+                 $db.ExecuteWithResults($DBPermsql).Tables.Rows
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException

PS C:\> $error[0] | select *


PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database
                        'DBTest1'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Execute with results failed for Database 'DBTest1'.  --->
                        Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. --->
                        System.Data.SqlClient.SqlException: Cannot resolve collation conflict between "Latin1_General_100_CI_AS_KS_WS_SC" and "Latin1_General_CI_AS_KS_WS" in add operator
                        occurring in SELECT statement column 11.
                        Cannot resolve collation conflict between "Latin1_General_100_CI_AS_KS_WS_SC" and "Latin1_General_CI_AS_KS_WS" in add operator occurring in SELECT statement column 12.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection sqlCommands)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(StringCollection query)
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs,
                        MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : FailedOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaPermission<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 43772
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

After some digging, I found this link that seems to show the problem: 
[https://dba.stackexchange.com/questions/122186/contained-db-collation-error](https://dba.stackexchange.com/questions/122186/contained-db-collation-error)

To test, I turned on debugging and pulled out the code from Get-DbaPermission.ps1 that sets $DBPermsql. The same "cannot resolve collation conflict" error resulted. I edited the lines that get column 11 and 12:

```
, [revokeStatement] = 'REVOKE ' + permission_name + ' ON ' + isnull(schema_name(o.object_id)+'.','')+OBJECT_NAME(major_id)+ ' FROM [' + USER_NAME(grantee_principal_id) +']'
, [grantStatement] = 'GRANT ' + permission_name + ' ON ' + isnull(schema_name(o.object_id)+'.','')+OBJECT_NAME(major_id)+ ' TO [' + USER_NAME(grantee_principal_id) + ']'
```

to include the `COLLATE CATALOG_DEFAULT` on the call to schema_name, and that resolved the issue. 

```
, [revokeStatement] = 'REVOKE ' + permission_name + ' ON ' + isnull(schema_name(o.object_id) COLLATE CATALOG_DEFAULT+'.','')+OBJECT_NAME(major_id)+ ' FROM [' + USER_NAME(grantee_principal_id) +']'
, [grantStatement] = 'GRANT ' + permission_name + ' ON ' + isnull(schema_name(o.object_id) COLLATE CATALOG_DEFAULT+'.','')+OBJECT_NAME(major_id)+ ' TO [' + USER_NAME(grantee_principal_id) + ']'
```

I don't know what the implications to making this change would be on older versions of SQL Server that do not support contained databases (and therefore don't have CATALOG_DEFAULT as a COLLATE option). 

## Environmental data

```
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2515
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2515
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Microsoft SQL Server 2016 (SP2-CU4) (KB4464106) - 13.0.5233.0 (X64)   Nov  3 2018 00:01:54   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```
PS C:\> get-module dbatools -listavailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.9.757    dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Start-DbaMigration, Copy-DbaDatabase...}
```

**Comment by mattbathje** [comment]
I played around with it again this morning, and it looks like if you use COLLATE DATABASE_DEFAULT (instead of CATALOG_DEFAULT) that also resolves the issue. 

```
, [revokeStatement] = 'REVOKE ' + permission_name + ' ON ' + isnull(schema_name(o.object_id) COLLATE DATABASE_DEFAULT+'.','')+OBJECT_NAME(major_id)+ ' FROM [' + USER_NAME(grantee_principal_id) +']'
, [grantStatement] = 'GRANT ' + permission_name + ' ON ' + isnull(schema_name(o.object_id) COLLATE DATABASE_DEFAULT+'.','')+OBJECT_NAME(major_id)+ ' TO [' + USER_NAME(grantee_principal_id) + ']'

**Comment by potatoqualitee** [comment]
thank you for the solution! ill try to resolve this within the week
