### ISSUE TITLE
[Bxug]

### ISSUE THREAD

**Issue by smtdba** [sqlcollaborative/dbatools#5390]
### Before submitting a bug report:

**Collect output of following command and paste below:**

```
### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.808\dbatools.psd1
Version : 0.9.808

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.775\dbatools.psd1
Version : 0.9.775
```

- [x] *Running latest release of dbatools*
- [x] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

> NOTE: `Copy-DbaDatabase` will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.

## Environmental data

```
### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1




### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.808\dbatools.psd1
Version : 0.9.808

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.775\dbatools.psd1
Version : 0.9.775
```

### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)   Oct 28 2016 18:17:30   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows 10 Enterprise 6.3 <X64> (Build 17763: ) (Hypervisor) 
```

## Errors Received

```powershell
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Object must implement IConvertible. ---> System.Management.Automation.MethodInvocationException: Exception calling "WriteToServer" with "1" argument(s): 
                        "The given value of type DateTimeOffset from the data source cannot be converted to type nvarchar of the specified target column." ---> System.InvalidOperationException: The 
                        given value of type DateTimeOffset from the data source cannot be converted to type nvarchar of the specified target column. ---> System.InvalidCastException: Failed to 
                        convert parameter value from a DateTimeOffset to a String. ---> System.InvalidCastException: Object must implement IConvertible.
                           at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                           at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
                           --- End of inner exception stack trace ---
                           at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
                           at System.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
                           --- End of inner exception stack trace ---
                           at System.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
                           at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
                           at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, 
                        TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 
                        source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataRow[] rows)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at Invoke-BulkCopy(Closure , FunctionContext )
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
                           --- End of inner exception stack trace ---
TargetObject          : localhost
CategoryInfo          : NotSpecified: (localhost:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Object must implement IConvertible.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.808\allcommands.ps1: line 109064
                        at Write-DbaDbTableData<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.808\allcommands.ps1: line 107716
                        at <ScriptBlock>, <No file>: line 2
PipelineIterationInfo : {0, 1}
```

## Steps to Reproduce

```sql
/*
    contents of file "D:\ps_root\sql\get-service-details.sql".
*/
SELECT 
    servicename
,   service_account
,   startup_type_desc
,   status_desc
,   process_id
,   last_startup_time  -- this is a datetime offset
-- I can get it to work by using the following line instead
--,   cast(last_startup_time as datetime) last_startup_time
,   filename
FROM sys.dm_server_services
```

```powershell
$ds = $null
$ds = Invoke-Sqlcmd2  `
        -ServerInstance 'server_name' `
        -InputFile 'D:\ps_root\sql\get-service-details.sql'

# Verify the data collected
# $ds | Out-GridView

if ($ds) {
    $ds | Write-DbaDataTable -SqlInstance 'localhost' -Database 'dbadmin' -Table '[dbo].[mssql_service_details]' -AutoCreateTable
    "Dataset written to table on my local machine" 
} else {
    "Empty Dataset, nothing written to table" | Out-Host
}
```

## Expected Behavior
I would expect a table to be created in my local database "dbadmin" with the name "[dbo].[mssql_service_details]".
All of the records contained in the $ds variable would be inserted into the table. 

## Actual Behavior
A table is created as expected that can hold the data from the $ds variable. 
The "last_startup_time" column is NVARCHAR(MAX) instead of DateTimeOffset or DateTime2.

I receive the warning: 
WARNING: [09:09:22][Write-DbaDbTableData] Failed to bulk import to [dbadmin].[dbo].[mssql_service_details] | Object must implement IConvertible.

No records are inserted into the new table.

**Comment by sqllensman** [comment]
Resolution of this issue requires adding the mapping of datetimeoffset to the $PStoSQLTypes hash table in the Write-DbaDataTable.

**Comment by potatoqualitee** [comment]
was this fixed in that commit @sqllensman ?

**Comment by sqllensman** [comment]
This should now be fixed.

**Comment by potatoqualitee** [comment]
thanks! :bowtie:
