### ISSUE TITLE
[Bug] Write-DbaDbTableData errors out against Azure SQL database

### ISSUE THREAD

**Issue by ThatShadowyPlace** [sqlcollaborative/dbatools#5547]
- [X] *Running latest release of dbatools*
- [X] Verified errors are not related to permissions
- [ ] Is this bug with `Copy-DbaDatabase`? You can replicate it using `Backup-DbaDatabase ... | Restore-DbaDatabase ...`

### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### dbatools Module version:

```
Name    : dbatools
Path    : C:\Users\XXXXXX\Documents\WindowsPowerShell\Modules\dbatools\0.9.828\dbatools.psd1
Version : 0.9.828
```

### SQL Server: 

```sql
Microsoft SQL Azure (RTM) - 12.0.2000.8   May  2 2019 20:11:13   Copyright (C) 2019 Microsoft Corporation 
```

## Errors Received

```
writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Exception: Login failed for user 'XXXXXXX'. ---> System.Data.SqlClient.SqlException:
                        Login failed for user 'XXXXXXX'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity,
                        SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String
                        newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance,
                        SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool
                        pool, String accessToken, Boolean applyTransientFaultHandling,
                        SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options,
                        DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection
                        owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool
                        pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey,
                        DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject,
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject,
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject,
                        UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection,
                        DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject,
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&
                        connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection
                        owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions,
                        DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection
                        outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry,
                        DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity
                        impersonatedIdentity)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           --- End of inner exception stack trace ---
TargetObject          : XXXXXXXXXXXXXX.database.windows.net
CategoryInfo          : ConnectionError: (XXXXXXXXXXXXXX.database.windows.net:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Login failed for user 'XXXXXXX'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function,
                        C:\Users\XXXXXX\Documents\WindowsPowerShell\Modules\dbatools\0.9.828\allcommands.ps1: line
                        110218
                        at Write-DbaDbTableData<Begin>,
                        C:\Users\XXXXXX\Documents\WindowsPowerShell\Modules\dbatools\0.9.828\allcommands.ps1: line
                        108699
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}



```

## Steps to Reproduce

```sql
create table dbo.TestTable ([Length] int);
```

```powershell
Write-DbaDbTableData -SqlInstance XXXXXXXXXXXXXX.database.windows.net -SqlCredential 'XXXXXXX' -Table 'dbo.TestTable' -InputObject 'test string' -Database XXXXXXXXX -Verbose

```

## Expected Behavior

Expecting it to insert the length of the InputObject parameter into the target table. Here is the output when I run the command against a non-Azure database:

```
VERBOSE: [15:15:15][Write-DbaDbTableData] FQTN processed: [XXXX].[dbo].[TestTable]
VERBOSE: [15:15:15][Invoke-BulkCopy] Importing in bulk to [XXXX].[dbo].[TestTable]
```

## Actual Behavior

It gives the below error. I believe it's coming from the Connect-SqlInstance call inside Write-DbaDbTableData since no initial database is passed in, and the target is an Azure SQL instance.

```
VERBOSE: [15:04:04][Write-DbaDbTableData] FQTN processed: [XXXXXXXXX].[dbo].[TestTable]
VERBOSE: [15:04:04][Connect-DbaInstance] Connecting to Azure: XXXXXXXXXXXXXX.database.windows.net
WARNING: [15:04:05][Write-DbaDbTableData] Error occurred while establishing connection to  | Login failed for user
'XXXXXXX'.
```

**Comment by ThatShadowyPlace** [comment]
I tried replacing the call to `Connect-SqlInstance` with `Connect-DbaInstance` and adding a parameter for the initial database, and it seems to work fine on Azure and SQL Server.

**Comment by wsmelton** [comment]
Support for integrated authentication to Azure SQL is in progress and will not be fixed immediately as we are trying to work out some details for properly handling it. 

As a workaround right now you can pass in a Azure SQL User and password credential for accessing the Azure SQL database.

**Comment by ThatShadowyPlace** [comment]
It does prompt me for a password, and I enter it. I tried it with both a "SQL Server Authentication" user and an "Active Directory - Password" user.

**Comment by wsmelton** [comment]
Azure SQL User functions correctly, I'm using it for scripts now to load data.

**Comment by potatoqualitee** [comment]
can you share some working sample code with fake values, shawn?

**Comment by wsmelton** [comment]
I'll have all the code published tomorrow, after my session at SQL Saturday Atlanta 😉 💯

**Comment by potatoqualitee** [comment]
LOL, ace! 🥇

**Comment by ThatShadowyPlace** [comment]
Seeing a working sample would be great - thanks!

**Comment by wsmelton** [comment]
Code has been published. Checkout the runbooks zip file here: https://github.com/sqlcollaborative/community-presentations/tree/master/shawn-melton

**Comment by wsmelton** [comment]
An example for easier reference though that I pull database information and I'm just dumping that output to an Azure SQL Database via SQL Login authentication. This is in the context of an Azure Automation Runbook where I'm pulling the credential....

```powershell
param (
    [string[]]$instance
)

#region AzureSqlDb
$azSqlServer = Get-AutomationVariable -Name 'AzureSqlServer'
$azSqlDb = Get-AutomationVariable -Name 'AzureSqlDatabase'
$azSqlCred = Get-AutomationPSCredential -Name 'dbatoolspbi.sql'
#endregion AzureSqlDb

$sqlCred = Get-AutomationPSCredential -Name 'sqlcred'

$writeParams = @{
    SqlInstance     = $azSqlServer
    Database        = $azSqlDb
    SqlCredential   = $azSqlCred
    Table           = 'databaseinfo'
    AutoCreateTable = $true
}
foreach ($i in $instance) {
    try {
        Write-Output "Working on: $i"
        $params = @{
            SqlInstance     = $i
            SqlCredential   = $sqlCred
            EnableException = $true
        }
        $results = Get-DbaDatabase @params
        foreach ($prop in $results) {
            Add-Member -InputObject $prop -MemberType NoteProperty -Name CaptureDate -Value (Get-Date) -Force
        }
        $results | Write-DbaDataTable @writeParams
    } catch {
        throw "$_"
    }
}
```

**Comment by ThatShadowyPlace** [comment]
Thanks for posting that. I don't have an Azure Automation runbook, but I tried creating the connection as a separate object, and it worked (the user is an Azure SQL User):

```powershell
$sqlInstance = Connect-DbaInstance -SqlInstance 'XXXXXXXXXXXXXX.database.windows.net' -SqlCredential 'XXXXXXX' -Database XXXXXXXXX
Write-DbaDbTableData -SqlInstance $sqlInstance -Table 'dbo.TestTable' -InputObject 'test string' -Database XXXXXXXXX -Verbose
```

I have to specify the database name twice, but that is not a big deal.

**Comment by potatoqualitee** [comment]
ill try to make that easier, let's see what i can do

**Comment by wsmelton** [comment]
I don't create a connection object.... You can just pass in the server name, credential and database and it works as-is. What is in a runbook is no different than what I would run on a physical server or my own desktop.

This does work as well:
```powershell
Write-DbaDbTableData -SqlInstance 'XXXXXXXXXXXXXX.database.windows.net' -SqlCredential 'XXXXXXX' -Database XXXXXXXXX -Table 'dbo.TestTable' -InputObject 'test string' -Verbose
```

**Comment by potatoqualitee** [comment]
nice, ty shawn
