### ISSUE TITLE
[Bug] Test-DbaDbCompatability uses Credential parameter and fails when a SQL Cred is passed

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#5666]
So I am looking at getting dbachecks running on Core (shhh ;-) ) and got this error when using SqlAuth for Test-DbaDbCompatability

### Environmental information
```
#### PowerShell version:

Name                           Value                                                                                                                     
----                           -----                                                                                                                     
PSVersion                      5.1.17763.503                                                                                                             
PSEdition                      Desktop                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                   
BuildVersion                   10.0.17763.503                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                           
WSManStackVersion              3.0                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                   




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.821\dbatools.psd1
Version : 0.9.821
```
```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0b

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : /home/robadmin/.local/share/powershell/Modules/dbatools/0.9.828/dbatools.psd1
Version : 0.9.828

#### SQL Server: 

Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)
        Sep 14 2018 13:53:44
        Copyright (C) 2017 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
```

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The target principal name is incorrect.  Cannot generate SSPI context. ---> 
                        System.Data.SqlClient.SqlException: The target principal name is incorrect.  Cannot generate SSPI context.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString 
                        connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean 
                        redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, 
                        String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, 
                        Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, 
                        DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 
                        waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, 
                        DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory 
                        connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : localhost,15591
CategoryInfo          : ConnectionError: (localhost,15591:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Test-DbaDbCompatibility,Stop-Function
ErrorDetails          : The target principal name is incorrect.  Cannot generate SSPI context.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.821\allcommands.ps1: line 109975
                        at Test-DbaDbCompatibility<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.821\allcommands.ps1: line 101047
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce

Running 

````Test-DbaDbCompatibility -SqlInstance 'localhost,15591' -Credential sqladmin````

returns the error above. Tested on PS 5.1, 6.2 and on WSL

Set the credential to $SQLCredential and command succeeds

WSL
![image](https://user-images.githubusercontent.com/6729780/58730688-c0169b80-83e4-11e9-9a79-fe67fa6001e2.png)

6.2

![image](https://user-images.githubusercontent.com/6729780/58730775-f81dde80-83e4-11e9-9f50-e3c273a558e3.png)

5.1

![image](https://user-images.githubusercontent.com/6729780/58730858-256a8c80-83e5-11e9-970a-efdbf982d357.png)

#### Expected Behavior

Should work with SqlCredential

#### Actual Behavior

Error as above!

**Comment by potatoqualitee** [comment]
thanks for the solution, will be fixed in 1.0
