### ISSUE TITLE
[Bug] Error with multiple commands in VSCode Powershell Integrated Console: Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies

### ISSUE THREAD

**Issue by flagmanchris** [sqlcollaborative/dbatools#5799]
### Environmental information
```
#### PowerShell version:

Name                           Value                                                                                                                                                                                     
----                           -----                                                                                                                                                                                     
PSVersion                      5.1.17134.765                                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                   
BuildVersion                   10.0.17134.765                                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                                                                   




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.0\dbatools.psd1
Version : 1.0.0

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.834\dbatools.psd1
Version : 0.9.834

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.825\dbatools.psd1
Version : 0.9.825

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.741\dbatools.psd1
Version : 0.9.741




```

#### SQL Server: 

```sql
Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64)   Sep 14 2018 13:53:44   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)
- [ ] Still buggy in powershell.exe

Only happens using powershell integrated console in VSCode

#### Errors Received

```


writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies. The system cannot find the file specified. ---> System.Exception: 
                        Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies. The system cannot find the file specified. ---> 
                        System.Management.Automation.MethodInvocationException: Exception calling "Open" with "0" argument(s): "The type initializer for 'System.Data.SqlClient.SqlAuthenticationProviderManager' threw 
                        an exception." ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception. ---> System.ArgumentException: 
                        Failed to instantiate an authentication provider with type 'Microsoft.Azure.Services.AppAuthentication.SqlAppAuthenticationProvider, Microsoft.Azure.Services.AppAuthentication' for 
                        'ActiveDirectoryInteractive'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies. The system cannot 
                        find the file specified.
                           at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean 
                        loadTypeFromPartialName, ObjectHandleOnStack type)
                           at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean 
                        loadTypeFromPartialName)
                           at System.Type.GetType(String typeName, Boolean throwOnError)
                           at System.Data.SqlClient.SqlAuthenticationProviderManager..ctor(SqlAuthenticationProviderConfigurationSection configSection)
                           --- End of inner exception stack trace ---
                           at System.Data.SqlClient.SqlAuthenticationProviderManager..ctor(SqlAuthenticationProviderConfigurationSection configSection)
                           at System.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
                           --- End of inner exception stack trace ---
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String 
                        newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String 
                        accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection 
                        owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, 
                        DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, 
                        DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal 
                        oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
                           --- End of inner exception stack trace ---
TargetObject          : localhost,14333
CategoryInfo          : ConnectionError: (localhost,14333:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaAgentJobHistory,Stop-Function
ErrorDetails          : Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies. The system cannot find the file specified.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.0\allcommands.ps1: line 79692
                        at Get-DbaAgentJobHistory<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.0\allcommands.ps1: line 17436
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce

Attempt to use command e.g. `Get-DbaDatabase -SqlInstance localhost:1433 -SqlCredential $sqlcred`
#### Expected Behavior
Command should run ;)

#### Actual Behavior
Error returned:
```
[Get-DbaDatabase] Error occurred while establishing connection to localhost,1433 | Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication' or one of its dependencies. The system
cannot find the file specified

**Comment by wsmelton** [comment]
I'm not able to reproduce this in my environment with VS Code Insiders.

If you can provide the `Help > about` info and also run this command and provide the output `code-insiders --list-extensions` or `code --list-extensions`.

**Comment by flagmanchris** [comment]
VSCode insiders:
```
Version: 1.36.0-insider (system setup)
Commit: c3fe2d8acde04e579880413ae4622a1f551efdcc
Date: 2019-06-20T05:20:10.276Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

```
dbatools.search
Equinusocio.vsc-material-theme
jmMeessen.jenkins-declarative-support
ms-azuretools.vscode-docker
ms-mssql.mssql
ms-vscode.powershell
secanis.jenkinsfile-support
zhuangtongfa.Material-theme
```

**Comment by flagmanchris** [comment]
tried previous version of dbatools and it also doesn't work on that (was working previously); some something to do with vscode insiders.....

**Comment by potatoqualitee** [comment]
Oh wow, it is! It works for me in regular Code, no problem yet I had the same DLL loading issue in Insiders.

I have zero idea how to even address this. @TylerLeonhardt any idea where to start troubleshooting this issue?

**Comment by wsmelton** [comment]
Can you provide the output of your path environment within your PA terminal of VS Code Indsiders?

**Comment by potatoqualitee** [comment]
I uninstalled it because it was too unstable for me :/

**Comment by wsmelton** [comment]
@flagmanchris can you provide your path output, and possibly the NET frameworks you have installed?

You can use this gist to gather the details: https://gist.github.com/wsmelton/48cb0fbd4a1516227b52b8bd55b49751

**Comment by brovoldt** [comment]
I am having this same issues where I can use DBATools in the ISE window or built in Powershell console but in VSCode it does not work.  

Here is my output of my path from the command window in VSCode

C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\ProgramData\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Users\xxxxxx\.dnx\bin
C:\Program Files\Microsoft DNX\Dnvm\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\
C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\
C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
C:\Program Files\dotnet\
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\Azure Data Studio\bin
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
C:\Users\xxxxxx\AppData\Local\Microsoft\WindowsApps

C:\Program Files\Azure Data Studio\bin
C:\Users\xxxxxx\AppData\Local\Programs\Microsoft VS Code\bin

Any help would be greatly appreciated......I had been using VSCode for a few months prior to this error occurring.

**Comment by potatoqualitee** [comment]
Thanks to all who filed an issue. Please check out 1.0.8 and let me know if that solves the problem.

**Comment by potatoqualitee** [comment]
Ahh hold a moment for 1.0.9, missed a spot

https://github.com/sqlcollaborative/dbatools/blob/development/internal/scripts/smoLibraryImport.ps1#L154

**Comment by flagmanchris** [comment]
Sorry for the dealy I've not been able to get back on this computer. I installed dbatools 1.0.9 but this didn't resolve issue. I updated windows insider after that which did resolve the issue.
Thanks,
Chris

**Comment by SolidCactus** [comment]
1.0.9 didn't do the trick for me unfortunately.

I'm not on Windows Insider so I'm wondering part of that update is doing the trick for @flagmanchris?

**Comment by potatoqualitee** [comment]
i got some error logs and will be taking a look today :thu

**Comment by flagmanchris** [comment]
I managed somehow to get mine broken again without doing anything! If you want me to provide any info let me know. I've not really any idea where to start looking at it myself. Not really causing a problem though as easy to work around it :)

**Comment by potatoqualitee** [comment]
Can you all also follow this thread and gather the info they are looking for? I will too: https://github.com/PowerShell/vscode-powershell/issues/2052#issuecomment-506426081

**Comment by potatoqualitee** [comment]
An idea is to move those new DLLs to a completely new folder. It seems the integrated terminal is loading it even though we didn't say to do so.

**Comment by RemkoD** [comment]
I encounter this error in Visual Studio Code **and** once in PowerShell ISE. Because i primary work in VSC I encounter the error there more often. Usually I can fix the issue by recycling the PowerShell session. One time this work-around didn't work and I had to restart my machine. 

We load the dbatools module from a 'scripttoprocess' script while importing one of our own modules. We use the Force parameter to reload the module. 
`Import-Module dbatools -Force -Global`

I will keep my eyes open for a reproduction. Thus far I have not found a repro scenario.

**Comment by potatoqualitee** [comment]
Thank you for the report, @RemkoD. Did you encounter this error in PowerShell ISE since 1.0.0?

**Comment by RemkoD** [comment]
@potatoqualitee, Currently I'm implementing dbatools in our tooling to replace SQL related cmdlets from various modules. I haven't worked with a version before 1.0.0. I have this issue since I've started to work with the dbatools module. I love what I've seen from the dbatools module so far. This bug is the only issue on my list. Unfortunately a nasty bug.

**Comment by lazarith** [comment]
I am getting the same error randomly after upgrading dbatools as well.  In vscode and ISE when trying to execute Invoke-DBAQuery command.

dbatools Version 1.0.12 installed in user profile

Powershell on Windows 10
Name                           Value                                                                                                                                                                                                                                                                                                                                                                                                                                                
PSVersion                      5.1.17134.765                                                                                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.17134.765                                                                                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1

**Comment by potatoqualitee** [comment]
Thanks @lazarith - the PowerShell team is currently looking into this, so hopefully we'll get some movement soon. Until then, you can restart your VS Code until it works again. Or this is what I'm doing basically default to powershell.exe thoo u lose the benefits of integrated terminal, but i dont use them anyway)

https://twitter.com/sqldbawithbeard/status/1143446045730529286
> Settings.json: "powershell.integratedConsole.showOnStartup": false

https://twitter.com/sqldbawithbeard/status/1143446045730529286
> I change the Run Selected Text in Active Terminal keyboard shortcut to F8 - then what you see in the editor panel will run in whichever terminal is active in the pane below which can then be PowerShell, pwsh, bash whatever :-)

**Comment by potatoqualitee** [comment]
@flagmanchris - can you delete app.config in bin\ and tell me if that fixes it? renaming it did not, but i cannot repro after deleting the file entirely (??)

**Comment by flagmanchris** [comment]
@potatoqualitee I've removed app.config and it appears to be working. I'll test out a little more and let you know

**Comment by flagmanchris** [comment]
Renaming or removing the file seem to fix it every time for me; putting the file back breaks it :)

**Comment by potatoqualitee** [comment]
sooo happy to hear! can you try the latest release? i removed the file and now write to disk dynamically

**Comment by flagmanchris** [comment]
Is this v1.0.15 master? I've tried that but I'm getting the error again :(

**Comment by potatoqualitee** [comment]
💔 i'm out of ideas

**Comment by RemkoD** [comment]
I've just got the error again (still on 1.0.11 though).  I've ran a few tests.

1. The module DbaTools worked fine in my PowerShell session.
2. I've recreated my PS session (killed and starting a new powershell process) to have a 'clean' session.
3. Imported DbaTools the same way as before, now I receive the error.

I've noticed that the dll 'Microsoft.Azure.Services.AppAuthentication' is actually loaded in the PS session with the issue:

![image](https://user-images.githubusercontent.com/20727407/60812965-fb01b100-a192-11e9-9fcd-9e02b3203b26.png)

The path is correct, on that location I can find the dll. 

4. Recreated my PS session again. 
5. Loaded  DbaTools the same way as before, this time i do not receive the error.

I noticed that the dlls are not loaded into the PS session.  

![image](https://user-images.githubusercontent.com/20727407/60813480-1faa5880-a194-11e9-9747-e4d046dbd7a5.png)

It's odd. Seems like sometimes the files are imported into the PS session causing the error and sometimes the files are not imported into the PS session.
