### ISSUE TITLE
[Bug] Error thrown when Import-Module dbatools

### ISSUE THREAD

**Issue by Teutenberg** [sqlcollaborative/dbatools#5837]
### Report
Executing PowerShell as "NT Authority\SYSTEM" fails to Import-Module dbatools.
NT Authority\SYSTEM is used when running scripts from scheduled tasks, or in my case from Octopus Deploy where the service is running under local system. 

### Environmental information
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2969
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2969
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
#### Host used
- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
```
PS C:\Windows\system32> whoami
nt authority\system
PS C:\Windows\system32> Import-Module dbatools
Join-DbaPath : Cannot bind argument to parameter 'Path' because it is an empty
string.
At line:21 char:79
+ ... -DbaPath -Path $([Environment]::GetFolderPath("MyDocuments")) -Child  ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-DbaPath], ParameterBindin
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl
   lowed,Join-DbaPath
```
#### Steps to Reproduce
- Download PSExec [https://download.sysinternals.com/files/PSTools.zip]
- Execute: C:\Temp\psexec.exe -i -s powershell.exe
- You now have PS session as NT Authority\SYSTEM
- Import-Module dbatools
- Error...

#### Expected Behavior

`Import-Module dbatools` succeeds.

#### Actual Behavior
`Import-Module dbatools` fails.

**Comment by Teutenberg** [comment]
Bug found in version 1.0.9 - PowerShell Install-Module dbatools:dbatools version 1.0.9
Bug not present in version 0.9.834 - PowerShell Install-Module dbatools:dbatools version 0.9.834

**Comment by wsmelton** [comment]
This is coming from a default path that we set for the configuration.

**Comment by wsmelton** [comment]
Reference to PR for background #5532

**Comment by wsmelton** [comment]
Full error stack for this error:

```
PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to
                        parameter 'Path' because it is an empty string.
                           at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParam
                        eterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object
                        parameterValue, Boolean recurseIntoCollections)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParamet
                        erInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
                        parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                        ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32
                        parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoV
                        alidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Co
                        llection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessor.Prepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean
                        ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Join-DbaPath], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Join-DbaPath
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\git\dbatools\internal\configurations\settings\paths.ps1: line 21
                        at <ScriptBlock>, C:\git\dbatools\internal\configurations\configuration.ps1: line 143
                        at <ScriptBlock>, C:\git\dbatools\dbatools.psm1: line 251
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

**Comment by potatoqualitee** [comment]
Does $home exist?

**Comment by potatoqualitee** [comment]
yes, it does k brb

**Comment by potatoqualitee** [comment]
hmmmm gotta work through this a bit more

![image](https://user-images.githubusercontent.com/8278033/60418005-29efb400-9be2-11e9-9991-7702ee560a10.png)

**Comment by wsmelton** [comment]
`$home` will exist under system accounts but it is a hidden system folder that you won't be able to access outside the service account's context.

**Comment by wsmelton** [comment]
On Windows machine OS @cl you can get different results as to where that `MyDocuments` path will take you....

This is Windows 10 1903 build:
![image](https://user-images.githubusercontent.com/11204251/60421104-c461ee80-9c06-11e9-8821-a6eb1486fc4e.png)

**Comment by potatoqualitee** [comment]
that may be because it's null and you are in system32. can you paste out the env variable without the ls?

**Comment by wsmelton** [comment]
It is null... I don't have a Documents folder in that hidden directory...

![image](https://user-images.githubusercontent.com/11204251/60421641-e27c1e80-9c07-11e9-9082-141b592ce7d9.png)

**Comment by potatoqualitee** [comment]
k ty!

**Comment by potatoqualitee** [comment]
@Teutenberg can you please test 1.0.11?
