### ISSUE TITLE
[Bug]`Test-DbaConnection` authenticating with current Windows account despite `$Credential` being passeddential` and ` 

### ISSUE THREAD

**Issue by mbobke** [sqlcollaborative/dbatools#5928]
__Please excuse the sanitation that I performed on the outputs below, I didn't want to include company information such as domain and hostnames.__

### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.145                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.145                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.21\dbatools.psd1
Version : 1.0.21
```

#### SQL Server: 

```sql
SQL Server Standard 2014 (12.0.5600)
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'DOMAIN\matt.bobke'. ---> System.Data.SqlClient.SqlException: Login failed for user 'DOMAIN\matt.bobke'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean 
                        redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& 
                        connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : TCP:SQLHOSTNAME
CategoryInfo          : ConnectionError: (TCP:SQLHOSTNAME:String) [], Exception
FullyQualifiedErrorId : dbatools_Get-DbaTcpPort
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\matt.bobke\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 80161
                        at Get-DbaTcpPort<Process>, C:\Users\matt.bobke\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 33498
                        at Test-DbaConnection<Process>, C:\Users\matt.bobke\Documents\WindowsPowerShell\Modules\dbatools\1.0.21\allcommands.ps1: line 66153
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

```powershell
> $SqlInstance = 'SQLHOSTNAME'
> $SqlCredential = $Credential = Get-Credential
> $testConnArgs = @{
>>         SqlInstance   = $SqlInstance
>>         SqlCredential = $SqlCredential
>>         Credential    = $Credential
>>         Verbose = $true
>>     }
> Test-DbaConnection @testConnArgs
```

#### Expected Behavior

Using alternative credentials for both `SqlCredential` and `Credential` with `Test-DbaConnection` should allow me to utilize my separate domain account with extended permissions (confirmed for both the remote machine itself and the machine's SQL instance) for this cmdlet. All other dbatools cmdlets that I've utilized so far with alternative credentials have been able to successfully authenticate without any errors while specifying alternative credentials.

#### Actual Behavior

```powershell
VERBOSE: [15:10:46][Test-DbaConnection] Getting local environment information
VERBOSE: [15:10:46][Resolve-DbaNetworkName] Resolving SQLHOSTNAME using .NET.Dns GetHostEntry
VERBOSE: [15:10:46][Resolve-DbaNetworkName] Resolving IPADDRESS using .NET.Dns GetHostByAddress
VERBOSE: [15:10:46][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [15:10:46][Get-DbaCmObject] [SQLHOSTNAME] Retrieving Management Information
VERBOSE: [15:10:46][Get-DbaCmObject] [SQLHOSTNAME] Accessing computer using Cim over WinRM
VERBOSE: [15:10:47][Get-DbaCmObject] [SQLHOSTNAME] Accessing computer using Cim over WinRM - Success
VERBOSE: [15:10:48][Resolve-DbaNetworkName] Resolving SQLHOSTNAME using .NET.Dns GetHostEntry
VERBOSE: [15:10:48][Test-DbaConnection] Checking remote acccess
VERBOSE: [15:10:48][Test-DbaConnection] Testing ping to SQLHOSTNAME
VERBOSE: [15:10:51][Test-DbaConnectionAuthScheme] Getting results for the following query: SELECT  SERVERPROPERTY('MachineName') AS ComputerName,
                            ISNULL(SERVERPROPERTY('InstanceName'), 'MSSQLSERVER') AS InstanceName,
                            SERVERPROPERTY('ServerName') AS SqlInstance,
                            session_id as SessionId, most_recent_session_id as MostRecentSessionId, connect_time as ConnectTime,
                            net_transport as Transport, protocol_type as ProtocolType, protocol_version as ProtocolVersion,
                            endpoint_id as EndpointId, encrypt_option as EncryptOption, auth_scheme as AuthScheme, node_affinity as NodeAffinity,
                            num_reads as NumReads, num_writes as NumWrites, last_read as LastRead, last_write as LastWrite,
                            net_packet_size as PacketSize, client_net_address as ClientNetworkAddress, client_tcp_port as ClientTcpPort,
                            local_net_address as ServerNetworkAddress, local_tcp_port as ServerTcpPort, connection_id as ConnectionId,
                            parent_connection_id as ParentConnectionId, most_recent_sql_handle as MostRecentSqlHandle
                            FROM sys.dm_exec_connections WHERE session_id = @@SPID.


ComputerName         : SQLHOSTNAME
InstanceName         : MSSQLSERVER
SqlInstance          : SQLHOSTNAME
SqlVersion           : 12.0.5600
ConnectingAsUser     : DOMAIN\matt.bobke.admin
ConnectSuccess       : True
AuthType             : Windows Authentication
AuthScheme           : NTLM
TcpPort              : Login failed for user 'DOMAIN\matt.bobke'.
IPAddress            : IPADDRESS
NetBiosName          : SQLHOSTNAME
IsPingable           : False
PSRemotingAccessible : True
DomainName           : DOMAIN
LocalWindows         : 10.0.18362.0
LocalPowerShell      : 5.1.18362.145
LocalCLR             : 4.0.30319.42000
LocalSMOVersion      : 15.100.0.0
LocalDomainUser      : True
LocalRunAsAdmin      : True
LocalEdition         : Desktop
```

You can see above that `Test-DbaConnection` sees that I am connecting as user `DOMAIN\matt.bobke.admin` but the `TcpPort` check with `Get-DbaTcpPort` attempts to use my current Windows account which does not have administrative permissions to SQL.

**Comment by mbobke** [comment]
I'm reopening this on a separate account.

**Comment by mcbobke** [comment]
#5929 is the new issue.
