### ISSUE TITLE
[Bug] Invoke-DbaDbShrink | -StepSize do not support large values

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#5958]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.3053                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.3053                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 


#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\dbatools\1.0.30\dbatools.psd1
Version : 1.0.30

```

```powershell
LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            German (Germany)
```

#### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2-CU7-OD) (KB4508636) - 13.0.5343.1 (X64) 
	Jun 14 2019 20:06:00 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process 
                        argument transformation on parameter 'StepSize'. Cannot convert value "2147483648" to type 
                        "System.Int32". Error: "Value was either too large or too small for an Int32." ---> 
                        System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value 
                        "2147483648" to type "System.Int32". Error: "Value was either too large or too small for an 
                        Int32." ---> System.Management.Automation.PSInvalidCastException: Cannot convert value 
                        "2147483648" to type "System.Int32". Error: "Value was either too large or too small for an 
                        Int32." ---> System.OverflowException: Value was either too large or too small for an Int32.
                           at System.Convert.ToInt32(Int64 value)
                           at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
                           at System.Management.Automation.LanguagePrimitives.ConvertNumeric(Object valueToConvert, 
                        Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider 
                        formatProvider, TypeTable backupTable)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertNumeric(Object valueToConvert, 
                        Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider 
                        formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object 
                        valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, 
                        IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type 
                        resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics 
                        engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics 
                        engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal 
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal 
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParamet
                        erInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 
                        parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, 
                        ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 
                        parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoV
                        alidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Co
                        llection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary 
                        psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at 
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object 
                        input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at 
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object 
                        input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean 
                        ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Invoke-DbaDbShrink], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Invoke-DbaDbShrink
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

``` powershell
Invoke-DbaDbShrink -SqlInstance sql2016 -Database Test -StepSize 2GB
```

#### Expected Behavior
It should run the shrink in a 2GB chunks

#### Actual Behavior
It gives the error pasted before.

To fix this we need to change the datatype of the -StepSize parameter. As stated on the docs, it works on bits but is using an INT32

**Comment by wsmelton** [comment]
Just need to bump up the type of the Parameter to `int64`.
