### ISSUE TITLE
Get-DbaService may return duplicate results when multiple SSRS instances exist

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#6003]
### Environmental information

```
#### PowerShell version:
Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.14409.1018                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.14409.1018                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\dbatools.psd1
Version : 1.0.38
```

```powershell
PS C:\Windows\system32> Get-Culture
LCID             Name             DisplayName                                                                                                                                                         
----             ----             -----------                                                                                                                                                         
1033             en-US            English (United States) 
```

#### SQL Server: 

```sql
Microsoft SQL Server Reporting Services 
© 2016 Microsoft 
Version 13.0.4446.0 
```

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "QueryCimRMInstance" with "4" argument(s): "WinRM 
                        cannot process the request. The following error with errorcode 0x80090322 occurred while using Kerberos authentication: An 
                        unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use 
                        HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config." ---> 
                        Microsoft.Management.Infrastructure.CimException: WinRM cannot process the request. The following error with errorcode 
                        0x80090322 occurred while using Kerberos authentication: An unknown security error occurred.  
                         Possible causes are:
                          -The user name or password specified are invalid.
                          -Kerberos is used when no authentication method and no user name are specified.
                          -Kerberos accepts domain user names, but not local user names.
                          -The Service Principal Name (SPN) for the remote computer name and port does not exist.
                          -The client and remote computers are in different domains and there is no trust between the two domains.
                         After checking for the above issues, try the following:
                          -Check the Event Viewer for events related to authentication.
                          -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use 
                        HTTPS transport.
                         Note that computers in the TrustedHosts list might not be authenticated.
                           -For more information about WinRM configuration, run the following command: winrm help config.
                           at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                           at Sqlcollaborative.Dbatools.Connection.ManagementConnection.QueryCimRMInstance(PSCredential Credential, String Query, 
                        String Dialect, String Namespace) in 
                        D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Connection\ManagementConnection.cs:line 907
                           at CallSite.Target(Closure , CallSite , Object , Object , String , String , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
                        exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : CimException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaCmObject<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 20031
                        at Get-DbaReportingService<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 74388
                        at Get-DbaService<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.38\allcommands.ps1: line 33322
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

When MyServer exists as a server with multiple instances of SSRS 2016:
```
Get-DbaService -ComputerName MyServer
```

#### Expected Behavior

Expected behavior is a result set containing one record per SSRS instance on the server.

#### Actual Behavior

Actual behavior is a result set containing multiple records per SSRS instance on the server.  The number of duplicates may be influenced by the instance count.  For example, if three instances of SSRS are installed, the result set may contain three copies of each instance service record, as shown in example below.
```powershell
PS C:\Users\MyUserName> Get-DbaService -ComputerName MyServer -Verbose | ft

VERBOSE: [07:43:55][Resolve-DbaNetworkName] Resolving MyServer using .NET.Dns GetHostEntry
VERBOSE: [07:43:56][Resolve-DbaNetworkName] Resolving x.x.x.x using .NET.Dns GetHostByAddress
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Accessing computer using Cim over WinRM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer] Accessing computer using Cim over WinRM - Success
VERBOSE: [07:43:56][Resolve-DbaNetworkName] Resolving MyServer.MyDomain using .NET.Dns GetHostEntry
VERBOSE: [07:43:56][Get-DbaService] Getting SQL Reporting Server services on MyServer.MyDomain
VERBOSE: [07:43:56][Get-DbaReportingService] Getting Reporting Server namespace on MyServer.MyDomain
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaReportingService] Getting version from the namespace RS_MYAPPDEV on MyServer.MyDomain.
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:56][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:56][Get-DbaReportingService] Getting version from the namespace RS_MSSQLSERVER on MyServer.MyDomain.
VERBOSE: [07:43:56][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaReportingService] Getting version from the namespace RS_MYAPPTST on MyServer.MyDomain.
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:57][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:57][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaService] Getting SQL Server namespace on MyServer.MyDomain
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success
VERBOSE: [07:43:58][Get-DbaService] Getting Cim class SqlService in Namespace ComputerManagement13 on MyServer.MyDomain.
VERBOSE: [07:43:58][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Retrieving Management Information
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM
VERBOSE: [07:43:58][Get-DbaCmObject] [MyServer.MyDomain] Accessing computer using Cim over DCOM - Success


ComputerName ServiceName           ServiceType InstanceName DisplayName                                 StartName               State   StartMode
------------ -----------           ----------- ------------ -----------                                 ---------               -----   ---------
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic
MyServer     ReportServer          SSRS        MSSQLSERVER  SQL Server Reporting Services (MSSQLSERVER) MyDomain\SQLSSRSMyServer Running Automatic
MyServer     ReportServer$MYAPPDEV SSRS        MYAPPDEV     SQL Server Reporting Services (MYAPPDEV)    MyDomain\SQLSSRSMYAPPDEV Running Automatic
MyServer     ReportServer$MYAPPTST SSRS        MYAPPTST     SQL Server Reporting Services (MYAPPTST)    MyDomain\SQLSSRSMYAPPTST Running Automatic

```

**Comment by wsmelton** [comment]
Please run the command with verbose output and append that to your post.

**Comment by SQLGB** [comment]
@wsmelton Inserted -verbose output into "Actual Behavior" section above.

**Comment by wsmelton** [comment]
@SQLGB Fred just fixed a bug in the CIM command that may have attributed to this issue...or at least I'd like to confirm. Can you pull the latest from dev and try the command against this server for me?

**Comment by SQLGB** [comment]
@wsmelton FYI, this is the first time I've tried doing a manual download and install of the dev branch, but I'm pretty sure I did it correctly.  However, the revisions to Get-DbaCmObject seem to help neither the issue I reported via 5998 or have any impact on this issue.  I'll be happy to try to test again tomorrow if you've got any tips or suggestions, or perhaps it would be easier if the Get-DbaCmObject changes get rolled into an updated production release.

**Comment by wsmelton** [comment]
So importing only the psd1 from the download, the issue still exists?

**Comment by SQLGB** [comment]
@wsmelton I’ll try that in the morning.  Earlier I downloaded the entire dev branch zip and used that.  I did see the new code in the error handling section, but as I mentioned earlier, it didn’t seem to help with the issue.

**Comment by SQLGB** [comment]
@wsmelton Might need some help / clarification here.  While importing only the psd1 this morning, I noticed that the Get-DbaCmObject code in allcommands.ps1 does not match the code in Get-DbaCmObject.ps1 -- shouldn't they be the same?

**Comment by SQLGB** [comment]
@wsmelton My prior comment was based on dev branch state as of about 14 hours ago; I see that 1.0.39 has been released since that time; testing that now.

**Comment by SQLGB** [comment]
@wsmelton Good and bad news.  Release 1.0.39 fixes issue 5998, but has no impact on 6003.

**Comment by wsmelton** [comment]
When you use the module from the repository `allcommands.ps1` is not used and will not match. That file is only rebuild for pushing to master.

**Comment by SQLGB** [comment]
@wsmelton OK, thanks.

I realize I'm getting a little off the topic and intent of this issue report, but, if I download the dev zip file, unzip it, rename the folder to dbatools, copy it to...
```
C:\Program Files\WindowsPowerShell\Modules\dbatools
```
... then import via...
```
import-module 'C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1'
```
... should that allow me to successfully use that dev code, or am I missing something here?  Because that's essentially what I did last night, and it seemed like the revised Get-DbaCmObject code was not present / not working.

I did review the pages below, and thought I'd addressed everything; there were no other versions installed at the same time.

https://dbatools.io/offline/
https://dbatools.io/download/

**Comment by wsmelton** [comment]
You can just download and extract to `C:\temp` if you want, then just do `Import-Module C:\temp\dbatools.psd1`.

**Comment by wsmelton** [comment]
I do not have a machine with SSRS installed right now so will have to get one setup before I can work and debug the command with this one. I know we had to adjust this command for SSRS 2016 because it went to a standalone install, the ComputerManagement you get with SQL Server 2016 does not have the ability to detect it anymore.

**Comment by SQLGB** [comment]
@wsmelton Yeah, I recall that; I'm the one who logged issue https://github.com/sqlcollaborative/dbatools/issues/3349.

**Comment by sqllensman** [comment]
I can reproduce issue and will submit fix in next 24 hours.  Caused by the new 2016 Report Server code

**Comment by SQLGB** [comment]
@sqllensman @potatoqualitee Thanks!
