### ISSUE TITLE
[Bug] Copy-DbaSsisCatalog looks for wrong assembly version: Microsoft.SqlServer.IntegrationServices.Common.ObjectModel v15

### ISSUE THREAD

**Issue by S1r-Lanzelot** [sqlcollaborative/dbatools#6049]
#### PowerShell version:
```
Name                           Value                                                                                                                                                      
----                           -----                                                                                                                                                      
PSVersion                      5.1.17134.858                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   10.0.17134.858                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                    
```

#### dbatools Module version:

```
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.46\dbatools.psd1
Version : 1.0.46
```

#### SQL Server: 

```sql
Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0 (X64)   Mar 11 2019 23:19:30   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

```


writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Could not load file or assembly 'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral, 
                        PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified. ---> 
                        System.Management.Automation.MethodInvocationException: Exception calling "Create" with "0" argument(s): "Could not load file or assembly 
                        'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. 
                        The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 
                        'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. 
                        The system cannot find the file specified.
                           at Microsoft.SqlServer.Management.IntegrationServices.Helpers.FormatSqlVariant(Object sqlVariant)
                           at Microsoft.SqlServer.Management.IntegrationServices.EnvironmentVariable.ScriptCreateInternal()
                           at Microsoft.SqlServer.Management.IntegrationServices.EnvironmentInfo.ScriptCreate()
                           at Microsoft.SqlServer.Management.Sdk.Sfc.SfcInstance.ScriptCRUD(SfcDependencyAction depAction, Object extraParam)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.SfcInstance.AccumulateScript(List`1 objList, SfcDependencyAction depAction, Object extraParam)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.SfcInstance.CRUDImplWorker(String operationName, SfcObjectState requiredState, SfcDependencyAction depAction, 
                        SfcObjectState finalState, Object extraParam)
                           at Microsoft.SqlServer.Management.IntegrationServices.EnvironmentInfo.Create()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
                           --- End of inner exception stack trace ---
TargetObject          : EnvironmentInfo[@Name='DEV']
CategoryInfo          : NotSpecified: (EnvironmentInfo[@Name='DEV']:EnvironmentInfo) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaSsisCatalog,Stop-Function
ErrorDetails          : Could not load file or assembly 'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral, 
                        PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.42\allcommands.ps1: line 81231
                        at Copy-DbaSsisCatalog<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.42\allcommands.ps1: line 9598
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce

1. Install latest version of dbatools
2. Run Copy-DbaSsisCatalog command moving over entire folder
ie: `Copy-DbaSsisCatalog -Source dev01 -Destination dev02 -Folder SomeFolder -Force`

#### Expected Behavior
All package and env information is moved over to the target server

#### Actual Behavior
I receive an error about not finding  `Microsoft.SqlServer.IntegrationServices.Common.ObjectModel`. I checked my GAC and I only have 14.0. To me it looks like this is looking for the 2019 assemblies which doesnt seem right.

**Comment by S1r-Lanzelot** [comment]
Most likely an issue with my machine.

**Comment by garethnewman** [comment]
I am also having this issue when trying to copy a folder. Not sure if it's me. I do have SSIS installed so I guess Microsoft.SqlServer.IntegrationServices.Common.ObjectModel is available.

Could not load file or assembly 'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral

**Comment by garethnewman** [comment]
@S1r-Lanzelot did you get it working?

**Comment by MURTAGH1974** [comment]
Tried this command this moring and i am getting the same referenced error

Copy-DbaSsisCatalog -Source $SourceServer -Destination $DestinationServer

WARNING: [11:40:40][Invoke-ProjectDeployment] Failed to deploy project. | Could not load file or assembly 'Microsoft.SqlServer.IntegrationServices.Common.ObjectModel, Version=15.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

SSIS is setup on the DestinationSever and it is the same version the source
