### ISSUE TITLE
[Bug] Import-DbaCSV fails on databases with non-alpha names

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#6064]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.48\dbatools.psd1
Version : 1.0.48

Name    : dbatools
Path    : C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.38\dbatools.psd1
Version : 1.0.38

Name    : dbatools
Path    : C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.33\dbatools.psd1
Version : 1.0.33

Name    : dbatools
Path    : C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.32\dbatools.psd1
Version : 1.0.32

Name    : dbatools
Path    : C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.27\dbatools.psd1
Version : 1.0.27



```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64) 
	Jun 15 2019 00:45:05 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18362: ) (Hypervisor)

```

### Report
When using `Import-DbaCsv` to import data into a database with a hypen in the name, a numeric name, or a name starting with a number, an incorrect syntax error is thrown.

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Invalid object name 'dbo.Actors'. ---> System.Data.SqlClient.SqlException: Invalid object name 'dbo.Actors'.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
                           at System.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Import-DbaCsv,Stop-Function
ErrorDetails          : Invalid object name 'dbo.Actors'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.48\allcommands.ps1: line 81293
                        at Import-DbaCsv<Process>, C:\Users\andy.levy\Documents\PowerShell\Modules\dbatools\1.0.48\allcommands.ps1: line 37917
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce
```
new-dbadatabase -SqlInstance localhost\sql17 -verbose -name "MyMovies";
new-dbadatabase -SqlInstance localhost\sql17 -verbose -name "1234";
new-dbadatabase -SqlInstance localhost\sql17 -verbose -name "1234Movies"

Import-DbaCsv -SqlInstance localhost\sql17 -AutoCreateTable -schema dbo -table "Actors" -verbose -database MyMovies -path 'C:\tmp\movies.csv' # Successful
Import-DbaCsv -SqlInstance localhost\sql17 -AutoCreateTable -schema dbo -table "Actors" -verbose -database 1234 -path 'C:\tmp\movies.csv' # Error
Import-DbaCsv -SqlInstance localhost\sql17 -AutoCreateTable -schema dbo -table "Actors" -verbose -database 1234movies -path 'C:\tmp\movies.csv' #Error

```
#### Expected Behavior
Successful import into the named database

#### Actual Behavior

Error as above

### Additional Info

I suspect that we need to wrap `$database` in square brackets on lines 513 and 516

```
$sql = "select count(*) from $Database.sys.tables where name = '$table' and schema_id=schema_id('$schema')"
```

While I'm here, should we consider using `Invoke-DbaQuery` here so that we can use a parameterized query instead of trusting that input from the user won't carry a SQL injection risk?

**Comment by wsmelton** [comment]
We carry SQL injection risk everywhere as how we deal with dynamic SQL has not been addressed in all commands. I do not see use of Invoke-DbaQuery as a fix for this and we need to look at that part differently to cover every bit of SQL we are calling in functions. Not something to address with this issue.
