### ISSUE TITLE
[Bug] Restore-DbaDatabase in PSCore throws exception

### ISSUE THREAD

**Issue by ksl28** [sqlcollaborative/dbatools#6069]
#### PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\ksladm\Documents\PowerShell\Modules\dbatools\1.0.49\dbatools.psd1
Version : 1.0.49
```

#### SQL Server: 
```
Microsoft SQL Server 2017 (RTM-CU16) (KB4508218) - 14.0.3223.3 (X64)   Jul 12 2019 17:43:08   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodException: Cannot find an overload for "GetExtension" and the argument count: "1".
                           at CallSite.Target(Closure , CallSite , Type , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaBackupInformation<Process>, C:\Users\ksladm\Documents\PowerShell\Modules\dbatools\1.0.49\allcommands.ps1: line 19349
                        at Restore-DbaDatabase<Process>, C:\Users\ksladm\Documents\PowerShell\Modules\dbatools\1.0.49\allcommands.ps1: line 59658
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce
```
$SMBServer = "10.10.10.10"
$SMBShare = "SQLShare$"
$SourceServer = "192.168.10.110"
$DestinationServer = "192.168.10.20"
$SourceDatabase = "SourceDatabase"
$DestinationDatabase = "NewDatabase"
$Script:Backup = Backup-DbaDatabase -SqlInstance $SourceServer -Database $SourceDatabase -Path "\\$SMBServer\$SMBShare" -CopyOnly -Type Full -Verify 
$Script:Backup | Restore-DbaDatabase -SqlInstance $DestinationServer -DatabaseName $DestinationDatabase -WithReplace
```
#### Expected Behavior
```
Successfully restored the database with no errors.
```

#### Actual Behavior
```
Instead of running the restore with no errors, it throws an error.
the command actually restores the SQL database, but still throws an error.
If running it with PS5.1 (5.1.17763.592), it performs the action just fine

```
![image](https://user-images.githubusercontent.com/53445047/65636334-5dc05700-dfe2-11e9-8552-be0d9f12401e.png)

**Comment by Stuart-Moore** [comment]
Was an issue with `-Verify` which looks like it was introduced in #6034 
$backup is actually being returned as an array
$backup[0] is the test output from the verify test
$backup[1] is the object output from Restore call for the verify
$backup[2] is the object output from Backup

In the example, it's throwing a warning as it tries to interpret $backup[0] as a folder. 

Throwing seas of blood because it's got no clue what to do with a Restore output object. In PS5.2 I get a nice yellow warning rather than a error. I'm guessing that's a difference in the way .Net and .NetCore are implemented.

And finally doing what it should be doing with $backup[2] and doing the restore, which is why you're seeing success
