### ISSUE TITLE
[Bug] Get-DbaDbState : Passing -SqlInstance param a hashtable returns conversion error

### ISSUE THREAD

**Issue by y-e-s-s-i-r** [sqlcollaborative/dbatools#6232]
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.74\dbatools.psd1
Version : 1.0.74

```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows Server 2016 Datacenter Evaluation 10.0 <X64> (Build 14393: ) (Hypervisor) 
/* REPLACE WITH output of @@VERSION */
```

<!-- Only if using non-English Database Engine -->
<!-- Paste output of `SELECT @@LANGUAGE` -->
```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [x ] powershell.exe
- [ ] ISE
- [x ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'SqlInstance'. Cannot convert value "System.Collections.Hashtable" to type 
                        "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value "System.Collections.Hashtable" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: 
                        System.Collections.Hashtable"" ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value "System.Collections.Hashtable" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: 
                        "Cannot convert value "System.Collections.Hashtable" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Collections.Hashtable"" ---> 
                        System.Management.Automation.PSInvalidCastException: Cannot convert value "System.Collections.Hashtable" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value "System.Collections.Hashtable" 
                        to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Collections.Hashtable"" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value 
                        "System.Collections.Hashtable" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Collections.Hashtable" ---> System.Management.Automation.PSArgumentException: 
                        Failed to interpret input as Instance: System.Collections.Hashtable
                           at Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter..ctor(Object Input) in C:\github\dbatools\bin\projects\dbatools\dbatools\Parameter\DbaInstanceParameter.cs:line 636
                           at lambda_method(Closure , Object )
                           at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                           at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext 
                        funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Get-DbaDbState], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-DbaDbState
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, E:\vsworkspace\src\monitoring\Get-SqlServiceStatus.ps1: line 13
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

Make hashtable of instance names ($table), pass table Get-DbadbState to via ForEach loop ( foreach ($name in $table){Get-DbadbState -SqlInstance $name}
#### Expected Behavior

cmdlet  is  executed against each instance and returns info

#### Actual Behavior

No info returned due to type error.

**Comment by wsmelton** [comment]
Yes, this is by design.

**Comment by wsmelton** [comment]
As documented our commands accept `[-SqlInstance] <DbaInstanceParameter[]> ` which indicates we only accept an array of values.

**Comment by potatoqualitee** [comment]
yah, unsure that I understand the code but this would work

```
$servers = @()
$servers += @{ server = "sql2017" }
$servers += @{ server = "sql2016" }

 $servers.server | Connect-DbaInstance
```

**Comment by wsmelton** [comment]
Use of `@()` means it is an array. A hashtable is a key/value pair using `${}`. In @potatoqualitee example `$servers.GetType()` will return a Base Type of `System.Array`. If you are working with a hashtable object you will get `System.Object` as the Base Type. With hashtables you are dealing with one single object in PowerShell, no matter how many "servers" you include. So looping over the object does nothing but return the whole object and then exit the loop.

In your the original example: `foreach ($name in $table) {Get-DbadbState -SqlInstance $name}`. The `$name` contains the whole object in `$table`, it is not iterating over anything and in the end you will end up with wrong results, or duplicate at least for Get commands.

To work with values in a hashtable you have to enumerate over the keys in order to work with the value pair:
![image](https://user-images.githubusercontent.com/11204251/70281212-11cb2480-1780-11ea-87c4-c26ef81f2569.png)

So for your code to work @y-e-s-s-i-r it has to be run as the following:

```
foreach ($name in $table.Keys) { 
    Get-DbadbState -SqlInstance $table[$name]
}
```

**Comment by potatoqualitee** [comment]
fab answer, thank you @wsmelton 🎈

**Comment by y-e-s-s-i-r** [comment]
Thanks for the explanation.
