### ISSUE TITLE
[Bug] Exception when running Get-DbaRegServer and have Azure Data Studio connections

### ISSUE THREAD

**Issue by stoycqs** [sqlcollaborative/dbatools#6292]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.17763.771                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.17763.771                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       




#### dbatools Module version:


Name    : dbatools
Path    : C:\Users\xxxxx\Documents\WindowsPowerShell\Modules\dbatools\1.0.20\dbatools.psd1
Version : 1.0.20

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.82\dbatools.psd1
Version : 1.0.82

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.72\dbatools.psd1
Version : 1.0.72




```

```

<!-- Only if using non-English versions of Windows -->
<!-- Paste output of `Get-Culture` -->
```powershell
# Replace with output of Get-Culture
```

#### SQL Server: 

```sql
/* REPLACE WITH output of @@VERSION */
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ ] powershell.exe
- [x ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```


PSMessageDetails      : 
Exception             : System.Management.Automation.SetValueInvocationException: Exception setting "ConnectionString": "Format of the initialization string does not conform to 
                        specification starting at index 107." ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 107.
                           at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& 
                        keyname, String& keyvalue)
                           at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
                           at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
                           at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
                           at Microsoft.SqlServer.Management.RegisteredServers.RegisteredServer.GetServerNameFromConnectionString(String connString)
                           at Microsoft.SqlServer.Management.RegisteredServers.RegisteredServer.set_ConnectionString(String value)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, 
                        MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaRegServer<Process>, C:\Users\xxx\Documents\WindowsPowerShell\Modules\dbatools\1.0.20\allcommands.ps1: line 31486
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

When a connection using Azure Data Studio is saved and run Get-DbaRegServer it generates the error in question... 

#### Expected Behavior

No

#### Actual Behavior

Exception

**Comment by potatoqualitee** [comment]
i will need to go and reopen all of these auto closures because there's been no movement and they're all legit. @wsmelton can you disable stale bot for now?

**Comment by wsmelton** [comment]
I changed it to stretch the days between stale and closure to 120 days. We can't really disable it the way it is setup.

I can go back and look to see if the Action works better now because that we can disable.

**Comment by jpomfret** [comment]
This is still an issue with 1.0.102

This is the part causing the issues - I'm not sure what it's used for, it's not returned as a default property - perhaps we could just remove it? I believe it is only relating to ADS connections but I don't have a CMS setup to test against right now - perhaps a goal for the weekend.

https://github.com/sqlcollaborative/dbatools/blob/6752767e1019a3150c2b7f35f66e22f966c2fa05/functions/Get-DbaRegServer.ps1#L178-L180

**Comment by wsmelton** [comment]
`ADS CMS <> SSMS CMS`

**Comment by jpomfret** [comment]
@wsmelton - not sure what you are implying there?
I mentioned CMS setup for testing if we removed that section - do you know what that 3 lines I highlighted is for and is it needed for ADS CMS servers?

**Comment by jpomfret** [comment]
The issue is that multiple connection strings are being returned for each server. I've added a PR to filter the results from Get-ADSConnection that should resolve the issue

![image](https://user-images.githubusercontent.com/981370/77855299-7dca1080-71e7-11ea-895a-9c628b947999.png)
