### ISSUE TITLE
[Bug]  Write-DbaDataTable fails when writing to Azure SQL Database

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#6337]
### Environmental information
```
#### PowerShell version:

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.14409.1018                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.14409.1018                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.88\dbatools.psd1
Version : 1.0.88

```
#### SQL Server: 
Microsoft SQL Azure (RTM) - 12.0.2000.8   Dec  4 2019 21:24:18   Copyright (C) 2019 Microsoft Corporation 

us_english
```

### Report

<!--
Things to consider:
- Errors received are not related to permissions?
- Have you tried the same command using powershell.exe instead of a hosted powershell instance like ISE or VS Code?
- If this refers to Copy-DbaDatabase can you replace the problem with Backup-DbaDatabase and Restore-DbaDatabase?
- Copy-DbaDatabase will not work in every environment and every situation. Instead, we try to ensure Backup & Restore work in your environment.
--> 


#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
```

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Reference to database and/or server name in 'db-au-e-dbareports-prod.Config.Priority_Copy' is not supported in this version of SQL Server. ---> 
                        System.Data.SqlClient.SqlException: Reference to database and/or server name in 'db-au-e-dbareports-prod.Config.Priority_Copy' is not supported in this version of 
                        SQL Server.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, 
                        TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, 
                        TdsParserStateObject stateObj)
                           at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
                           at System.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                           --- End of inner exception stack trace ---
TargetObject          : sqlsvr-au-e-dbareports-prod.database.windows.net
CategoryInfo          : NotSpecified: (sqlsvr-au-e-dba...ase.windows.net:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Reference to database and/or server name in 'db-au-e-dbareports-prod.Config.Priority_Copy' is not supported in this version of SQL Server.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.88\allcommands.ps1: line 82217
                        at Write-DbaDbTableData<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.88\allcommands.ps1: line 74402
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```



#### Steps to Reproduce
```
$Cred = Get-Credential -UserName $Username -Message 'Enter Password'
$svr = Connect-DbaInstance -SqlInstance $AzureSqlInstance -Database $AzureDB -SqlCredential $Cred

$sql = 'SELECT Field FROM [dbo].[TableName]'
$Data = $svr | Invoke-DbaQuery -Query $sql -As DataTable

Write-DbaDataTable -SqlInstance $svr -Database $AzureDB -Table '[dbo].[TableName_Copy]' -InputObject $Data -AutoCreateTable

```


#### Expected Behavior

<!--
What did you expect to happen?

Data from existing table should be copied to new table (which is auto created)
-->

#### Actual Behavior
New table is created but actual Bulk Copy operation fails 
Error is:

WARNING: [12:48:11][Write-DbaDbTableData] Failed to bulk import to [db-au-e-dbareports-prod].[Config].[Priority_Copy] | Reference to database and/or server name in 'db-au-e-dbareports-prod.C
onfig.Priority_Copy' is not supported in this version of SQL Server.

Based on the current code this is expected action as the DestinationTableName set in the BulkCopy object is being passed with a Fully Qualified Three-part name
(Line 519): $bulkCopy.DestinationTableName = $fqtn 

As per the error message, this syntax is not supported for a SQLDatabase instance

**Comment by sqllensman** [comment]
When investigating the code to fix this issue there also seems to be another issue in the Write-DbaDbTableData function

When the code is creating the BulkCopy object it is using different options for Azure databases based on assumption that $server.ConnectionContext.ConnectionString will include the databse

```

        if ($server.isAzure) {

            # will for sure have the database in connstring

            $bulkCopy = New-Object Data.SqlClient.SqlBulkCopy($server.ConnectionContext.ConnectionString, $bulkCopyOptions)

        } else {

            $bulkCopy = New-Object Data.SqlClient.SqlBulkCopy("$($server.ConnectionContext.ConnectionString);Database=$databaseName", $bulkCopyOptions)

        }

```

This does not seem to be accurate as the connection seems to be specifically created earlier in code 
```
$server = Connect-SqlInstance -SqlInstance $SqlInstance -SqlCredential $SqlCredential
```
without a database context.
