### ISSUE TITLE
[Bug] Error importing CSV via Import-DbaCsv on Microsoft SQL Azure (The connection's current state is open.)

### ISSUE THREAD

**Issue by craigguest** [sqlcollaborative/dbatools#6399]
# Environmental information

#### PowerShell version:

```
Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.18362.628                                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.18362.628                                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                           
```

#### dbatools Module version:

```
Name    : dbatools
Path    : C:\Users\user\Documents\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101
```

#### SQL Server: 
```
Microsoft SQL Azure (RTM) - 12.0.2000.8 	Feb 26 2020 10:26:43 	Copyright (C) 2019 Microsoft Corporation
```

### Report

When attempting to upload a CSV to Microsoft SQL Azure the following error occurs:

```
WARNING: [14:13:11][Import-DbaCsv] Error occurred while establishing connection to TCP:name.database.windows.net,1433 | The connection was not closed. The connection's current state is open.
```

This happens when running the following dbatools command:

```powershell
Import-DbaCsv -Path Results.csv -SqlInstance "TCP:name.database.windows.net,1433" -Database "ResultDatabase" -Table 'Results' -SqlCredential $credentials -NotifyAfter 1000;
```

The csv contains the output from a JMeter test run and is 71MB in size, and is the format below:

```csv
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect
2020/03/04 06:03:17.987,95,/styles.css,200,OK,Thread Group-ThreadStarter 1-1,text,true,,46466,426,2,2,https://mywebsite.com/styles.css,95,0,0
```

The same command works when run against a SQL Server instance with the following version:

```
Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64) 	Nov 16 2019 01:14:50 	Copyright (C) 2017 Microsoft Corporation	Developer Edition (64-bit) on Linux (CentOS Linux 7 (Core))
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Import-DbaCsv<End>, C:\Users\user\Documents\WindowsPowerShell\Modules\dbatools\1.0.101\allcommands.ps1: line 38895
                        at <ScriptBlock>, C:\Users\user\JMeter\Upload.ps1: line 47
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

```powershell
Import-DbaCsv -Path Results.csv -SqlInstance "TCP:name.database.windows.net,1433" -Database "ResultDatabase" -Table 'Results' -SqlCredential $credentials -NotifyAfter 1000;
```

#### Expected Behavior

CSV should be uploaded with output every 1000 items.

#### Actual Behavior

```
WARNING: [14:13:11][Import-DbaCsv] Error occurred while establishing connection to TCP:name.database.windows.net,1433 | The connection was not closed. The connection's current state is open.
```

**Comment by wsmelton** [comment]
Try removing the tcp from your server name.

**Comment by craigguest** [comment]
@wsmelton thanks for the suggestion. I just tried it without TCP then tried without TCP and 1433, both resulted in the same error.

**Comment by wsmelton** [comment]
Can you connect using Connect-DbaInstance and then pass that connection object to the import commands?

**Comment by craigguest** [comment]
@wsmelton same error with the following code:

```powershell
$connection = Connect-DbaInstance -SqlInstance "TCP:name.database.windows.net,1433" -Database "ResultDatabase" -SqlCredential $credentials;
Import-DbaCsv -SqlInstance $connection -Database $connection -Table 'Results' -Path $file.FullName -NotifyAfter 1000;
```

The `Connect-DbaInstance` call works fine, and Invoke-DbaQuery works with those credentials too.

**Comment by jaxnoth** [comment]
We were able to replicate this locally as well.  I haven't put in a PR yet, but replacing
$sqlconn.Open() on line 469 with
if ($sqlconn.State -ne 'Open') {  $sqlconn.Open()  }
fixes the issue.
The previous line $sqlconn = $server.ConnectionContext.SqlConnectionObject
uses an already open connection.
