### ISSUE TITLE
Connect-DbaInstance doesn't use SqlCredential to connect [Bug]

### ISSUE THREAD

**Issue by cfradenburg** [sqlcollaborative/dbatools#6474]
### Environmental information

```
#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\dbatools.psd1
Version : 1.0.104

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.101\dbatools.psd1
Version : 1.0.101



```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64) 
	Jan 23 2020 21:00:04 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received
**This resulted in multiple errors and I'm including details of all below**

```

PSMessageDetails      : 
Exception             : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.ServiceBrokerEnum, Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.
                        File name: 'Microsoft.SqlServer.ServiceBrokerEnum, Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
                           at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
                           at System.Reflection.RuntimeConstructorInfo.get_Signature()
                           at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
                           at System.RuntimeType.FilterApplyMethodBase(MethodBase methodBase, BindingFlags methodFlags, BindingFlags bindingFlags, CallingConventions callConv, Type[] argumentTypes)
                           at System.RuntimeType.GetConstructorCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Boolean allowPrefixLookup)
                           at System.RuntimeType.GetConstructorImpl(BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
                           at System.Type.GetConstructor(BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
                           at System.Type.GetConstructor(Type[] types)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                           at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
                        
                        
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\internal\scripts\libraryimport.ps1: line 120
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\internal\scripts\libraryimport.ps1: line 133
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\dbatools.psm1: line 209
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```
```

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Connect" with "0" argument(s): "Failed to connect to server serverA."
                         ---> Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server serverA.
                         ---> System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'domainB\userBSO'.
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:1d4d0526-0c61-499b-a606-3dace362ffbb
                        Error Number:18456,State:1,Class:14
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ConnectionFailureException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-DbaInstance<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1: line 2562
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```
```

PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'domainB\userBSO'.
                         ---> System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'domainB\userBSO'.
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:1d4d0526-0c61-499b-a606-3dace362ffbb
                        Error Number:18456,State:1,Class:14
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], Exception
FullyQualifiedErrorId : dbatools_Connect-DbaInstance
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1: line 83029
                        at Connect-DbaInstance<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1: line 2583
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

```Powershell
PS C:\Users\userB> $acred = Get-Credential

PowerShell credential request
Enter your credentials.
User: domainA\userA
Password for user domainA\userA: ****************

PS C:\Users\userB> Connect-DbaInstance serverA -SqlCredential $acred -Debug
```

#### Expected Behavior
The credential stored in `$acred` to be used and to actually connect because it has permissions.

#### Actual Behavior

Verbose and debug output:
```
DEBUG: [14:38:59][Connect-DbaInstance] Can't connect to serverA | Login failed for user 'domainB\userB'.
Exception: C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\allcommands.ps1:83029
 Line |
83029 |          throw $records[0]
      |          ~~~~~~~~~~~~~~~~~
      | Login failed for user 'domainB\userB'.
```

Note: this also doesn't work correctly if the Powershell session user does have access to the system.  In that case it returns the object but the `ConnectingAsUser` isn't the credential passed in but rather the user that launched Powershell

**Comment by wsmelton** [comment]
Not able to duplicate (I get the expected error)...however as well none of us have a multi-domain setup that will allow us to test for this use case so if you can troubleshoot and submit the PR it would be appreciated.

![image](https://user-images.githubusercontent.com/11204251/79263734-fd4b1700-7e58-11ea-8928-ee6fda88e6bd.png)

**Comment by cfradenburg** [comment]
I also see an issue when both logins are in the same domain but while digging into that I noticed that I'm only seeing the issue when using Powershell 7.  If I use Powershell 5 it works as expected.  If I just do an `import-module dbatools` in PS7 I get this error:

```

PSMessageDetails      : 
Exception             : System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.ServiceBrokerEnum, Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.
                        File name: 'Microsoft.SqlServer.ServiceBrokerEnum, Version=15.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
                           at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
                           at System.Reflection.RuntimeConstructorInfo.get_Signature()
                           at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
                           at System.RuntimeType.FilterApplyMethodBase(MethodBase methodBase, BindingFlags methodFlags, BindingFlags bindingFlags, CallingConventions callConv, Type[] argumentTypes)
                           at System.RuntimeType.GetConstructorCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Boolean allowPrefixLookup)
                           at System.RuntimeType.GetConstructorImpl(BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
                           at System.Type.GetConstructor(BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
                           at System.Type.GetConstructor(Type[] types)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
                           at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                           at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                           at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                           at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
                        
                        
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\internal\scripts\libraryimport.ps1: line 120
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\internal\scripts\libraryimport.ps1: line 133
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.104\dbatools.psm1: line 209
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

I don't get that error when importing in PS5.

**Comment by wsmelton** [comment]
Yep. There is likely SMO adjustments that need to be done for PS7 proper support.
