### ISSUE TITLE
[Bug] Get-DbaDbBackupHistory: Error occurred while establishing connection to listener

### ISSUE THREAD

**Issue by zrbrc** [sqlcollaborative/dbatools#6502]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                      
----                           -----                                                                                                                                                      
PSVersion                      5.1.14393.3471                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   10.0.14393.3471                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                    

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.107\dbatools.psd1
Version : 1.0.107
```

```powershell
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: The system cannot find the file specified ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while 
                        establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is 
                        configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> 
                        System.ComponentModel.Win32Exception: The system cannot find the file specified
                           --- End of inner exception stack trace ---
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, 
                        Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData 
                        reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, 
                        DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, 
                        DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean 
                        onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, 
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : dhsssbdbcls1ls1
CategoryInfo          : ConnectionError: (dhsssbdbcls1ls1:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaDbBackupHistory,Stop-Function
ErrorDetails          : The system cannot find the file specified
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 82910
                        at Get-DbaDbBackupHistory<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 21983
                        at Get-DbaDbBackupHistory<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.107\allcommands.ps1: line 22078
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```
#### Steps to Reproduce

Run: 
```
Get-DbaDbBackupHistory -SqlInstance 'dhsssbdbcls1ls1,15150' -Database 'perfmon' -verbose
```

#### Expected Behavior

Receive results for all backups for all replicas.

#### Actual Behavior
```
VERBOSE: [15:15:27][Get-DbaDbBackupHistory] Fetching history from replicas for db perfmon
WARNING: [15:15:42][Get-DbaDbBackupHistory] Error occurred while establishing connection to dhsssbdbcls1ls1 | The system cannot find the file specified
VERBOSE: [15:15:42][Get-DbaDbBackupHistory] Executing sql query on [dhsssbdbcls1ls1,15150].
VERBOSE: [15:15:42][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [15:15:42][Get-DbaDbBackupHistory] 0 result-groups found.
```

If I pass -AgCheck I get the backups from the primary replica. Without that param, I get the error above. Possibly the port is not being passed and thus not finding the replicas. We use non-standard ports for everything so we have to specify everywhere. This also slows down Backup-DbaDatabase since it does a Get-DbaDbBackupHistory call at the end and it doesnt show the output of the backup then. I tried against 3 different listeners with the same results. 

First bug report, be gentle, thanks.

**Comment by wsmelton** [comment]
This is sadly by design, it is a limitation of SMO and secondary replicas using custom, non-default ports. :( 

// @Stuart-Moore

**Comment by wsmelton** [comment]
#6251 has some background on this and it is not something we will be able to support....but Stuart may be able to troubleshoot it where we find a viable solution.

**Comment by zrbrc** [comment]
So why have the option with AgCheck, shouldnt AgCheck code be the default and only option then? I cant run a backup without a warning and I get no output bc it's doing a BackupHistory check against the Ag that fails, I cant pass it AgCheck. This happens whether I run it against the listener or the primary. Am I just being dumb and doing something wrong?

**Comment by wsmelton** [comment]
The option is there because it is not common for SQL Server installations to use custom ports. (I've been in the business for over 15 years and I've only touched 2 or 3 environments that had a SQL Server instance with a custom port...and that was mostly in the federal gov't.)

**Comment by klindberg70** [comment]
Hello, I have the same error as zrbc and I agree that -agcheck should be the default. Very confusing when connecting to the primary replica instance and it is complaining about connecting to the AG listener
get-dbadbbackuphistory -sqlinstance "localhost\inst01"  -database xxx_prod -Last -Verbose -force
VERBOSE: [11:36:32][Get-DbaDbBackupHistory] Fetching history from replicas for db xxx_prod
WARNING: [11:36:47][Get-DbaDbBackupHistory] Error occurred while establishing connection to AG01xxx | The system cannot find the file specified

**Comment by Stuart-Moore** [comment]
AgCheck actually stops checking for the AG. Without it, if GBH finds it's been pointed at an AG it recursively calls itself against each node, AgCheck stops us getting into a infinite recursion loop

Didn't realise this had actually made it past PR, as I thought we'd parked it due to the port issue that Shawn mentions above.

Unless we can find a programmatic way of getting the remote port then we'll have to put something to stop it doing anything if there isn't a default port on the other end. Or put something in to allow a WMI call if the calling user has admin rights on the remote Server OS

**Comment by andreasjordan** [comment]
Here are some ideas: https://github.com/sqlcollaborative/dbatools/issues/6604#issuecomment-671782948

**Comment by andreasjordan** [comment]
Hi @zrbrc , please update dbatools to the lastest version and try to use Get-DbaAgBackupHistory.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
