### ISSUE TITLE
[Bug] Write-DbaDbTable not Creating table when -AutocreateTable switch is used for some table names

### ISSUE THREAD

**Issue by ca6dsm** [sqlcollaborative/dbatools#6537]
### Environmental information

```powershell
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU11) (KB4527378) - 13.0.5598.27 (X64)   Nov 27 2019 18:09:22   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
/* REPLACE WITH output of @@LANGUAGE */
```

#### Host used

- [ X] powershell.exe
- [ X] ISE
- [ X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ X] Still buggy in powershell.exe

#### Errors Received

 System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'RAIDR_SNOMED_DEV.AArdvark.EREV'.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&
                        dataReady)
                           at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
                           at System.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                        ClientConnectionId:fab57d40-4e9c-4b04-a83d-ee4e303451e6
                        Error Number:208,State:1,Class:16
                           --- End of inner exception stack trace ---
-->

#### Steps to Reproduce

$script:serverMain='XXXX'
$script:dbMain = 'XXXXXXXXXXXXXXXXXXXX'   
$queryType='AArdvark'
$commaSymbol=','
$filePath='EVET.csv'
$headerList = ('EMIS Number,Date,Concept ID,Value,Secondary Value,Organisation Code').Split($commaSymbol)
$rowStart=7

$QueryName = 'EVET'
$dataTable = Import-Csv $filePath -Header $headerList |  Select-Object -Skip $rowStart  |  ConvertTo-DbaDataTable 
Write-DbaDataTable  -SqlInstance $serverMain -InputObject $dataTable -Database $dbMain -AutoCreateTable -Schema $queryType -Table $queryName ##-EnableException 

$QueryName='EREV'
Write-DbaDataTable  -SqlInstance $serverMain -InputObject $dataTable -Database $dbMain -AutoCreateTable -Schema $queryType -Table $queryName -EnableException 

#### Expected Behavior

Both Tables should be created in Aardvark Schema .

#### Actual Behavior
EVET is created but EREV isn't from debug details looks like create table isn't firing for EREV

**Comment by ca6dsm** [comment]
is this ok first one i have submitted

**Comment by nvarscar** [comment]
Found the problem:
https://github.com/sqlcollaborative/dbatools/blob/fb31a745b0ea3554c0ca0a3e77955227c8791f5e/functions/Write-DbaDbTableData.ps1#L459

Schema comparison logic is not correct, which would then skip table creation when table name already exists in a different schema. Will file a PR
