### ISSUE TITLE
[Set-DbaAgentSchedule] FrequencyInterval no longer accepting strings (e.g. EveryDay)

### ISSUE THREAD

**Issue by JMLemieux** [sqlcollaborative/dbatools#6554]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.1007                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.1007                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.111\dbatools.psd1
Version : 1.0.111




```

```powershell
4105             en-CA            English (Canada)
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU18) (KB4527377) - 14.0.3257.3 (X64)   Nov 16 2019 01:14:50   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```sql
us_english
```

#### Host used

- [X] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```


ErrorRecord                 : Cannot process argument transformation on parameter 'FrequencyInterval'. Cannot convert 
                              value "EveryDay" to type "System.Int32". Error: "Input string was not in a correct 
                              format."
WasThrownFromThrowStatement : False
Message                     : Cannot process argument transformation on parameter 'FrequencyInterval'. Cannot convert 
                              value "EveryDay" to type "System.Int32". Error: "Input string was not in a correct 
                              format."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot 
                              process argument transformation on parameter 'FrequencyInterval'. Cannot convert value 
                              "EveryDay" to type "System.Int32". Error: "Input string was not in a correct format." 
                              ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot 
                              convert value "EveryDay" to type "System.Int32". Error: "Input string was not in a 
                              correct format." ---> System.Management.Automation.PSInvalidCastException: Cannot 
                              convert value "EveryDay" to type "System.Int32". Error: "Input string was not in a 
                              correct format." ---> System.FormatException: Input string was not in a correct format.
                                 at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& 
                              number, NumberFormatInfo info, Boolean parseDecimal)
                                 at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
                                 at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo 
                              formatInfo)
                                 at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext 
                              context, CultureInfo culture, Object value)
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.LanguagePrimitives.ConvertStringToInteger(Object 
                              valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, 
                              IFormatProvider formatProvider, TypeTable backupTable)
                                 at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object 
                              valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, 
                              IFormatProvider formatProvider, TypeTable backupTable)
                                 at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, 
                              Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable 
                              backupTypeTable)
                                 at 
                              System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics 
                              engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean 
                              bindingScriptCmdlet)
                                 --- End of inner exception stack trace ---
                                 at 
                              System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics 
                              engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean 
                              bindingScriptCmdlet)
                                 at 
                              System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal 
                              parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                 --- End of inner exception stack trace ---
                                 at 
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                              funcContext, Exception exception)
                                 at 
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
                              dollarUnderbar, Object inputToProcess)
                                 at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                                 at System.Management.Automation.CommandProcessorBase.Complete()
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] 
                              Invoke(System.Collections.IEnumerable)
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, 
                              Exception& exceptionThrown, ExecutionOptions options)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

```

#### Steps to Reproduce

New-DbaAgentSchedule -SqlInstance $MyInstance -Schedule "TestSchedule" -FrequencyType Daily -FrequencyInterval Everyday -StartDate "21000101" -EndDate "21000102" -StartTime "000000" -EndTime "000000"
Set-DbaAgentSchedule -SqlInstance $MyInstance -Schedule "TestSchedule" -FrequencyType Daily -FrequencyInterval Everyday -StartDate "21000101" -EndDate "21000102" -StartTime "010000" -EndTime "000000"

#### Expected Behavior

Since New-DbaAgentSchedule accepts FrequencyInterval likes "Everyday" or "Wednesday" I would expect Set-DbaAgentSchedule to support the same. This assumption is also supported by the documentation, the second example gives an error: https://docs.dbatools.io/#Set-DbaAgentSchedule

#### Actual Behavior

FrequencyInterval in Set-DbaAgentSchedule only accepts integers:  
Cannot process argument transformation on parameter 'FrequencyInterval'. Cannot convert 
                              value "EveryDay" to type "System.Int32". Error: "Input string was not in a correct 
                              format."

**Comment by wsmelton** [comment]
related #6492
