### ISSUE TITLE
[Bug] - Write-DbaDbTableData - Fails to bulk insert when using windows credentials in -SqlCredential

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbatools#6618]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.17763.316                                                                                                                 
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.17763.316                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                       

#### dbatools Module version:

Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.112\dbatools.psd1
Version : 1.0.112


```

#### SQL Server:
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### Report

Trying to collect data with one windows domain account and then use a second windows domain account to insert that data into a table using the -SqlCredential parameter on Write-DbaDbTableData (using alias in screenshot, tested with function name, same error).

In this screenshot I am running PowerShell as the account that doesn't have access to the Test database, and then the $creds variable contains credentials that do have access.

The error message is that the original (TestUserTwo) doesn't have access. I will say the table gets created when I use -AutoCreateTable, just the bulk insert fails.

```
WARNING: [14:56:49][Write-DbaDbTableData] Failed to bulk import to [Test].[dbo].[SpaceTest] | Login failed for user 'pomfret\TestUserTwo'.
```

![image](https://user-images.githubusercontent.com/981370/85569793-c187b700-b62a-11ea-81b5-0c278ad45b21.png)

I have narrowed it down to this line - there is nothing that passes through the SqlCredential:
https://github.com/sqlcollaborative/dbatools/blob/development/functions/Write-DbaDbTableData.ps1#L237

I have tried a few things, closest I got was if we have a SqlCredential wrap it in Invoke-Command, but now I get an error:
```
Method invocation failed because [Deserialized.System.Data.SqlClient.SqlBulkCopy] does not contain a method named 'WriteToServer'.
```
I get this when I replace lines 236-240 with this:
```
if($SqlCredential) {
                    Invoke-Command -ComputerName . -Credential $SqlCredential -ScriptBlock {
                        $bulkCopyRemote = $using:bulkCopy
                        $bulkCopyRemote.WriteToServer($using:dataTable)
                        if ($using:rowCount -is [int]) {
                            Write-Progress -id 1 -activity "Inserting $using:rowCount rows" -status "Complete" -Completed
                        }
                    }
                } else {
                    $bulkCopy.WriteToServer($DataTable)
                    if ($rowCount -is [int]) {
                        Write-Progress -id 1 -activity "Inserting $rowCount rows" -status "Complete" -Completed
                    }
                }
```

Anyone have some suggestions on how we could approach this - am I looking over something simple?

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'pomfret\TestUserTwo'. ---> System.Data.SqlClient.SqlException: Login failed for user 
                        'pomfret\TestUserTwo'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, 
                        SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, 
                        SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean 
                        applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object 
                        poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, 
                        DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, 
                        Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory 
                        connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at System.Data.SqlClient.SqlBulkCopy.CreateOrValidateConnection(String method)
                           at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
TargetObject          : dscsvr2
CategoryInfo          : NotSpecified: (dscsvr2:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Login failed for user 'pomfret\TestUserTwo'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.112\allcommands.ps1: line 83168
                        at Write-DbaDbTableData<End>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.112\allcommands.ps1: line 75290
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Steps to Reproduce

- run PowerShell as a windows account that does not have access to the destination database
- Use Write-DbaDbTableData with the -SqlCredential parameter
```
Get-DbaDiskSpace | 
Write-DbaDbTableData -SqlInstance dscsvr2 -Database Test -Table SpaceTest -AutoCreateTable -SqlCredential $creds
```
- Credentials used should be windows account that has permissions to the destination database (it works with a SQL login)

#### Expected Behavior

- Table is created if it doesn't exist - currently works
- Data is inserted - fails

#### Actual Behavior

- Table is created
- Error on bulk insert

**Comment by wsmelton** [comment]
This won't support Windows Credential if I recall because you cannot use that credential type with the SqlBulk namespace/dll.

**Comment by jpomfret** [comment]
Hey @wsmelton, thanks for reply. Do you think it would be possible to execute that part in script block or something like that?

**Comment by wsmelton** [comment]
Scriptblock could lead to compatibility issues I would think because we are using the dll for it that we ship with the module. So if you do a remote call and the version on the server is older or newer, slim chance it may give different results or functionality.

**Comment by andreasjordan** [comment]
Hi @jpomfret - I had a look at this and I think the problem is here:
https://github.com/sqlcollaborative/dbatools/blob/fd4b4e53c90503d89ba902aead0cb7d164ef35fa/functions/Write-DbaDbTableData.ps1#L522

We use the wrong constructor. See:
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy

We use `SqlBulkCopy(String, SqlBulkCopyOptions)` but should use `SqlBulkCopy(SqlConnection, SqlBulkCopyOptions, SqlTransaction)` to use the connection inside $server.

To connect to the correct database we should move this line after we know the database and use the `-Database` parameter there to get the correct connection context (will definitly work in the new code path of Connect-DbaInstance, maybe also in the old one):
https://github.com/sqlcollaborative/dbatools/blob/fd4b4e53c90503d89ba902aead0cb7d164ef35fa/functions/Write-DbaDbTableData.ps1#L373

Do you have time to work on this? If not, give me a sign, I will try to set this up later this month.

**Comment by potatoqualitee** [comment]
I imagine Jess is busy - she is writing the book right now, please feel free to take it, @andreasjordan !

**Comment by andreasjordan** [comment]
There was a related problem reported on Slack, so I opened #7460 ...
