### ISSUE TITLE
[Bug] Copy-DbaLogin - error when copying disabled sql login (New-DbaLogin)

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#6708]
### Environmental information

```powershell
PowerShell Version        : 7.0.3
dbatools latest installed : 1.0.115
Culture of OS             : ru-RU
```
#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2-CU12) (KB4536648) - 13.0.5698.0 (X64)   Feb 15 2020 01:47:30   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
```

```sql
us_english
```

### Report

Using Copy-DbaLogin to copy **disabled** sqllogin will fail with an error message - `Incorrect syntax near 'DENY_WINDOWS'.`

#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [x] pwsh.exe

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

```powershell
> $error[3].Exception.InnerException.InnerException.InnerException

TargetSite     : System.Data.DataSet ExecuteWithResults(System.String, Boolean)
StackTrace     :    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection sqlCommands)
                    at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(StringCollection query)
                    at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
Message        : An exception occurred while executing a Transact-SQL statement or batch.
Data           : {}
InnerException : System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DENY_WINDOWS'.
                    at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                 ClientConnectionId:c9ea327f-ce8e-4309-aa32-36a38fbb35ea
                 Error Number:102,State:1,Class:15
HelpLink       :
Source         : Microsoft.SqlServer.ConnectionInfo
HResult        : -2146233087
```
#### Steps to Reproduce

Copy disabled sqllogin.

#### Expected Behavior

Login copied with all attributes, in a disabled state.

#### Actual Behavior

```powershell
> Get-DbaLogin -SqlInstance srv-sql-dr02 -Login audit_depo

ComputerName : <sourceSQLInstance1>
InstanceName : MSSQLSERVER
SqlInstance  : <sourceSQLInstance1>
Name         : <loginname>
LoginType    : SqlLogin
CreateDate   : 28.11.2016 13:15:23
LastLogin    :
HasAccess    : True
IsLocked     : False
IsDisabled   : True
```
```powershell
> Copy-DbaLogin -Source <sourceSQLInstance1> -Destination <sourceSQLInstance2> -Login <loginname>

Type             Name       Status Notes
----             ----       ------ -----
Login - SqlLogin <loginname> Failed
```

**Comment by andreasjordan** [comment]
Based on the error messgae, the failing lines are probably in New-DbaLogin (485 and 486):

```
                                    $sql = "ALTER LOGIN [$loginName] DENY_WINDOWS" #check this one
                                    $null = $server.Query($sql)
```

Can you run `Copy-DbaLogin` with `-Verbose` and provide the output?

**Comment by andreasjordan** [comment]
Can you provide `(Get-DbaLogin -SqlInstance srv-sql-dr02 -Login audit_depo).DenyWindowsLogin`?

**Comment by andreasjordan** [comment]
It will not help with this issue, but: Where does this "DENY_WINDOWS" comes from? It is not part of the "ALTER LOGIN" syntax - or is it some special undocumented syntax?

**Comment by Zhunya** [comment]
> Can you provide `(Get-DbaLogin -SqlInstance srv-sql-dr02 -Login audit_depo).DenyWindowsLogin`?
`True`

The problem is in New-DbaLogin.

**Comment by wsmelton** [comment]
The issue here is going to be PowerShell (pwsh). What version are you using @Zhunya?

**Comment by wsmelton** [comment]
Scratch that last comment...

@Zhunya can you clarify your steps provided? You cannot call our Copy command pointing to the same instance for both source and destination, which will error with a null index and not reference the DENY_WINDOWS error.

I'm not able to reproduce this in 2019 and should be no difference with 2016 for login processing...

![image](https://user-images.githubusercontent.com/11204251/89335713-022d1400-d65e-11ea-9ea6-4f34863f11ee.png)

**Comment by Zhunya** [comment]
I have Powershell 7.0.3

There is more data from error:

```powershell

MethodInvocationException: E:\GitHub\sqlcollaborative\functions\New-DbaLogin.ps1:486
Line |
 486 |                                      $null = $server.Query($sql)
     |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Query" with "1" argument(s): "Exception calling "ExecuteWithResults" with "1" argument(s): "Execute with results failed for Database 'master'. ""

PS > $error[3].Exception.InnerException.InnerException.InnerException

TargetSite     : System.Data.DataSet ExecuteWithResults(System.String, Boolean)
StackTrace     :    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(StringCollection sqlCommands)
                    at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteWithResults(StringCollection query)
                    at Microsoft.SqlServer.Management.Smo.Database.ExecuteWithResults(StringCollection sqlCommands)
Message        : An exception occurred while executing a Transact-SQL statement or batch.
Data           : {}
InnerException : System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'DENY_WINDOWS'.
                    at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                 ClientConnectionId:c9ea327f-ce8e-4309-aa32-36a38fbb35ea
                 Error Number:102,State:1,Class:15
HelpLink       :
Source         : Microsoft.SqlServer.ConnectionInfo
HResult        : -2146233087

```

**Comment by wsmelton** [comment]
Reference to `DENY_WINDOWS` appears to have been an assumption that was not verified before publishing. The DenyWindowsLogin simply references to issuing `GRANT/CONNECT TO SQL...`.

**Comment by wsmelton** [comment]
@Zhunya this is not a valid path for our module's functions: `E:\GitHub\sqlcollaborative\functions\New-DbaLogin.ps1:486`

Can you clarify how you are trying to use the command and provide full steps to reproduce what you are using/doing?

**Comment by Zhunya** [comment]
Here is new test:

```powershell

> Get-DbaLogin -SqlInstance srv-sql-dr02 -Login TestDisabledCopying

ComputerName : SRV-SQL-DR02
InstanceName : MSSQLSERVER
SqlInstance  : SRV-SQL-DR02
Name         : TestDisabledCopying
LoginType    : SqlLogin
CreateDate   : 04.08.2020 22:25:46
LastLogin    :
HasAccess    : True
IsLocked     : False
IsDisabled   : False


PS C:\Users\strutinskyad> Copy-DbaLogin -Source srv-sql-dr02 -Destination srv-sql06 -Login TestDisabledCopying

Type             Name                Status Notes
----             ----                ------ -----
Login - SqlLogin TestDisabledCopying Failed

PS C:\Users\strutinskyad> $error[0]

Write-Error: E:\GitHub\sqlcollaborative\functions\Copy-DbaLogin.ps1:362
Line |
 362 |  …             Stop-Function -Message "Failed to add $newUserName to $de …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Incorrect syntax near 'DENY_WINDOWS'.
```

![image](https://user-images.githubusercontent.com/14327077/89336578-47733500-d6a2-11ea-9be2-dd00f2336e5e.png)

Here are more properties on login:

```powershell

> Get-DbaLogin -SqlInstance srv-sql-dr02 -Login TestDisabledCopying | Select-Object -Property *

ComputerName              : SRV-SQL-DR02
InstanceName              : MSSQLSERVER
SqlInstance               : SRV-SQL-DR02
LastLogin                 :
Parent                    : [srv-sql-dr02]
AsymmetricKey             :
Certificate               :
CreateDate                : 04.08.2020 22:25:46
Credential                :
DateLastModified          : 04.08.2020 22:25:46
DefaultDatabase           : master
DenyWindowsLogin          : True
HasAccess                 : True
ID                        : 608
IsDisabled                : False
IsLocked                  : False
IsPasswordExpired         : False
IsSystemObject            : False
Language                  : us_english
LanguageAlias             : English
LoginType                 : SqlLogin
MustChangePassword        : False
PasswordExpirationEnabled : False
PasswordHashAlgorithm     : ShaOne
PasswordPolicyEnforced    : False
Sid                       : {2, 193, 111, 184…}
WindowsLoginAccessType    : NonNTLogin
Events                    : Microsoft.SqlServer.Management.Smo.LoginEvents
Name                      : TestDisabledCopying
ParentCollection          : {##crtProcessKiller##, ##MS_PolicyEventProcessingLogin##, ##MS_PolicyTsqlExecutionLogin##, 1C_test…}
Urn                       : Server[@Name='SRV-SQL-DR02']/Login[@Name='TestDisabledCopying']
Properties                : {Name=CreateDate/Type=System.DateTime/Writable=False/Value=08/04/2020 22:25:46, Name=DateLastModified/Type=System.DateTime/Writable=False/Value=08/04/2020 22:25:46, Name=DefaultDatab
                            ase/Type=System.String/Writable=True/Value=master, Name=DenyWindowsLogin/Type=System.Boolean/Writable=True/Value=True…}
ServerVersion             : 13.0.5698
DatabaseEngineType        : Standalone
DatabaseEngineEdition     : Enterprise
ExecutionManager          : Microsoft.SqlServer.Management.Smo.ExecutionManager
UserData                  :
State                     : Existing
IsDesignMode              : False
```

**Comment by wsmelton** [comment]
How did you create the login you are copying?

**Comment by Zhunya** [comment]
I have created him with SSMS GUI

**Comment by wsmelton** [comment]
Can you provide what version of SSMS you have in use?

**Comment by Zhunya** [comment]
Downloaded dbatools 1.0.115 from PS Gallery
Put in C:\Program Files\WindowsPowerShell\Modules\dbatools

```powershell

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```powershell

PS > Copy-DbaLogin -Source localhost -Destination srv-sql06 -Login TestDisabledCopying

Type             Name                Status Notes
----             ----                ------ -----
Login - SqlLogin TestDisabledCopying Failed


PS > $error[0]
Stop-Function : Incorrect syntax near 'DENY_WINDOWS'.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1:8385 char:21
+ ...             Stop-Function -Message "Failed to add $newUserName to $de ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SRV-SQL06:PSObject) [Write-Error], Exception
    + FullyQualifiedErrorId : dbatools_Copy-Login,Stop-Function

```

**Comment by Zhunya** [comment]
> How did you create the login you are copying?



> Can you provide what version of SSMS you have in use?

![image](https://user-images.githubusercontent.com/14327077/89340887-1c401400-d6a9-11ea-9aa9-976fbf12f9ef.png)

**Comment by wsmelton** [comment]
Tested it on 18.5.1 and it does set that property.

PR just rips out the logic and call to the T-SQL statement. If it can't set the property via SMO there are larger issues in play anyway.

**Comment by andreasjordan** [comment]
```
$SecurePassword = ('P@ssw0rd#' | ConvertTo-SecureString -AsPlainText -Force)
New-DbaLogin -SqlInstance WIN10\SQL2014 -Login TestDeny -SecurePassword $SecurePassword -DenyWindowsLogin -Verbose
New-DbaLogin -SqlInstance WIN10\SQL2016 -Login TestDeny -SecurePassword $SecurePassword -DenyWindowsLogin -Verbose
New-DbaLogin -SqlInstance WIN10\SQL2017 -Login TestDeny -SecurePassword $SecurePassword -DenyWindowsLogin -Verbose
New-DbaLogin -SqlInstance WIN10\SQL2019 -Login TestDeny -SecurePassword $SecurePassword -DenyWindowsLogin -Verbose
(Get-DbaLogin -SqlInstance WIN10\SQL2014 -Login TestDeny).DenyWindowsLogin
(Get-DbaLogin -SqlInstance WIN10\SQL2016 -Login TestDeny).DenyWindowsLogin
(Get-DbaLogin -SqlInstance WIN10\SQL2017 -Login TestDeny).DenyWindowsLogin
(Get-DbaLogin -SqlInstance WIN10\SQL2019 -Login TestDeny).DenyWindowsLogin

VERBOSE: Performing the operation "Creating login TestDeny on WIN10\SQL2014" on target "WIN10\SQL2014".
VERBOSE: [08:26:29][New-DbaLogin] Setting TestDeny DenyWindowsLogin to True
VERBOSE: [08:26:29][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [08:26:29][New-DbaLogin] Successfully added TestDeny to WIN10\SQL2014.
WARNING: [08:26:29][New-DbaLogin] Failed to set deny windows login priviledge TestDeny on WIN10\SQL2014. | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Login] does not contain a method named 'Apply'.
VERBOSE: Performing the operation "Creating login TestDeny on WIN10\SQL2016" on target "WIN10\SQL2016".
VERBOSE: [08:26:29][New-DbaLogin] Setting TestDeny DenyWindowsLogin to True
VERBOSE: [08:26:29][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [08:26:29][New-DbaLogin] Successfully added TestDeny to WIN10\SQL2016.
WARNING: [08:26:29][New-DbaLogin] Failed to set deny windows login priviledge TestDeny on WIN10\SQL2016. | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Login] does not contain a method named 'Apply'.
VERBOSE: Performing the operation "Creating login TestDeny on WIN10\SQL2017" on target "WIN10\SQL2017".
VERBOSE: [08:26:29][New-DbaLogin] Setting TestDeny DenyWindowsLogin to True
VERBOSE: [08:26:29][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [08:26:29][New-DbaLogin] Successfully added TestDeny to WIN10\SQL2017.
WARNING: [08:26:29][New-DbaLogin] Failed to set deny windows login priviledge TestDeny on WIN10\SQL2017. | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Login] does not contain a method named 'Apply'.
VERBOSE: Performing the operation "Creating login TestDeny on WIN10\SQL2019" on target "WIN10\SQL2019".
VERBOSE: [08:26:29][New-DbaLogin] Setting TestDeny DenyWindowsLogin to True
VERBOSE: [08:26:29][New-DbaLogin] Adding as login type SqlLogin
VERBOSE: [08:26:29][New-DbaLogin] Successfully added TestDeny to WIN10\SQL2019.
WARNING: [08:26:29][New-DbaLogin] Failed to set deny windows login priviledge TestDeny on WIN10\SQL2019. | Method invocation failed because [Microsoft.SqlServer.Management.Smo.Login] does not contain a method named 'Apply'.
True
True
True
True
```

So the command works, but does more than needed and still has a bug in there.

**Comment by wsmelton** [comment]
So the apply method must have been what was causing the catch block to be hit.

Odd this just showed up though and the test never catches it. I did verify that before the PR and we are testing the windows deny parameter.

**Comment by wsmelton** [comment]
AH...hold up. I know where all this is coming from. This is code that all got added when @nvarscar setup the login cloning PR.  #6577

**Comment by wsmelton** [comment]
He might be able to shed light on where the `Apply()` and `DENY_WINDOWS` came from...

**Comment by wsmelton** [comment]
#6713 #6712

**Comment by nvarscar** [comment]
RE Apply(), this should've been Alter(), but was never caught in the tests, I'll put up a PR shortly.
As for DENY_WINDOWS (or DENY_LOGIN?), the function attempts to create a login using T-SQL if SMO fails for whatever reason. Those never were tested, as the SMO never failed in tests. It's been a while so I'm not sure what's the right syntax to set that property in T-SQL, as the CREATE LOGIN page doesn't have anything like this. ALTER LOGIN only has `ENABLE | DISABLE`.

**Comment by wsmelton** [comment]
When I traced it on 2019 it just causes `GRANT/CONNECT TO SQL` to be executed. Which somewhat makes sense, why they chose to call it "Windows" though I don't know because it applies to SQL Logins and Windows Auth logins.

**Comment by nvarscar** [comment]
okay, so this seems to be the fix then:
```
if ($currentDenyWindowsLogin) {
                            try {
                                $newLogin.DenyWindowsLogin = $true
                                $newLogin.Apply()
                                Write-Message -Level Verbose -Message "Login $loginName has been denied on $instance."
                            } catch {
                                $newLogin.Parent.Query("DENY CONNECT SQL TO [{0}]" -f $newLogin.Name)
                                Stop-Function -Message "Failed to set deny windows login priviledge $loginName on $instance." -Category InvalidOperation -ErrorRecord $_ -Target $instance -Continue
                            }
                        }
```
Testing it now
