### ISSUE TITLE
Copy-DbaDbTableData

### ISSUE THREAD

**Issue by turnerowen** [sqlcollaborative/dbatools#6871]
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on 
                        parameter 'SqlInstance'. Cannot convert value "System.Object[]" to type 
                        "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Object[]" 
                        ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value "System.Object[]" to type 
                        "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Object[]" 
                        ---> System.Management.Automation.PSInvalidCastException: Cannot convert value "System.Object[]" to type 
                        "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Object[]" 
                        ---> System.Management.Automation.PSArgumentException: Failed to interpret input as Instance: System.Object[]
                           at Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter..ctor(Object Input) in 
                        D:\Code\Github\dbatools\bin\projects\dbatools\dbatools\Parameter\DbaInstanceParameter.cs:line 587
                           at lambda_method(Closure , Object )
                           at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, 
                        Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, 
                        Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean 
                        recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                           at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, 
                        IFormatProvider formatProvider, TypeTable backupTypeTable)
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object 
                        inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object 
                        inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, 
                        CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, 
                        CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, 
                        MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, 
                        CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 
                        arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] 
                        pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Copy-DbaDbTableData], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Copy-DbaDbTableData
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
PipelineIterationInfo : {}

#### Steps to Reproduce

$Instances = Get-Content "C:\instances.txt"
Copy-DbaDbTableData -SqlInstance $Instances -Destination myInstance -Database myDatabase -Table MyTable

#### Expected Behavior

Inline with a number of other dbatools modules I thought the script would run for each instance defined in the text file instances.txt.  
I use the same .txt files with other dbatools modules and if I replace $Instances with an instance name, the script executes without issue.

#### Actual Behavior

Copy-DbaDbTableData : Cannot process argument transformation on parameter 'SqlInstance'. Cannot convert value "System.Object[]" to type 
"Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to interpret input as Instance: System.Object[]"

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.120
Culture of OS             : en-US

#### SQL Server:

Microsoft SQL Server 2016 (SP2-CU13) (KB4549825) - 13.0.5820.21 (X64)   May 22 2020 07:24:35   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

us_english

**Comment by niphlod** [comment]
you can have multiple dests with that syntax but not multiple sources....

**Comment by turnerowen** [comment]
I was hoping to be able to consolidate data from multiple instances into one central database.  If it does not currently work in this way, could this be considered as a new feature?
