### ISSUE TITLE
Install-DbaFirstResponderToolKit attempts to install on 2005 and lower yet everything fails

### ISSUE THREAD

**Issue by tonyfountain** [sqlcollaborative/dbatools#6908]
When executing Install-DbaFirstResponderToolKit on a 2005 instance (or earlier), the cmdlet attempts to deploy the .sql files but all of them fail since they're not compatible with 2005 or earlier.

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
```
PSMessageDetails      : 
Exception             : System.Exception: Cannot assign a default value to a local variable.
                        Must declare the scalar variable "@SQLVersion".
                        Must declare the scalar variable "@ServerName".
                        Must declare the scalar variable "@db".
                        Cannot assign a default value to a local variable.
                        Must declare the scalar variable "@db".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@dbq".
                        Must declare the scalar variable "@cmd".
                        Must declare the scalar variable "@msg2".
                        Must declare the scalar variable "@msg1".
                        Must declare the scalar variable "@db".
                        Incorrect syntax near 'END'. ---> System.Data.SqlClient.SqlException: Cannot assign a default value to a local variable.
                        Must declare the scalar variable "@SQLVersion".
                        Must declare the scalar variable "@ServerName".
                        Must declare the scalar variable "@db".
                        Cannot assign a default value to a local variable.
                        Must declare the scalar variable "@db".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@thisdb".
                        Must declare the scalar variable "@dbq".
                        Must declare the scalar variable "@cmd".
                        Must declare the scalar variable "@msg2".
                        Must declare the scalar variable "@msg1".
                        Must declare the scalar variable "@db".
                        Incorrect syntax near 'END'.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                           at System.Data.SqlClient.SqlDataReader.get_MetaData()
                           at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
                           at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean 
                        describeParameterEncryptionRequest)
                           at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean 
                        asyncWrite, Boolean inRetry)
                           at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
                           at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
                           at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
                           at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
                           at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
TargetObject          : PRD-SQL-05
CategoryInfo          : NotSpecified: (PRD-SQL-05:String) [], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.123\allcommands.ps1: line 84112
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.123\allcommands.ps1: line 47819
                        at Install-DbaFirstResponderKit<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.123\allcommands.ps1: line 39780
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce
Install-DbaFirstResponderKit -SqlInstance <any 2005 instance> -Database 'master'

#### Expected Behavior
If earlier than SQL 2005, then skip installing the files (similar to the skip logic that already exists for other procedures).  If SQL Server 2005, then install the stored procedures in the 'Deprecated' folder instead.

#### Actual Behavior
Various errors are spit out due to using syntax not compatible with 2005 and earlier.

### Environmental information

```powershell
PowerShell Version        : 5.1.14393.3471
dbatools latest installed : 1.0.123
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2005 - 9.00.5057.00 (X64)   Mar 25 2011 13:33:31   Copyright (c) 1988-2005 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.2 (Build 9200: ) 
```

```sql
us_english
```

**Comment by andreasjordan** [comment]
The idea is good, but we have a problem...

We had a lot of discussions about this command some time ago and the way it works was redesigned. 
At the moment, only the non-deprecated files are copied to the $LocalCachedCopy - so there is no way to install the deprecated files.

We would have to copy them as well and then test for the version of the SqlInstance and install the correct versions.

I can do the change, but as I don't have a 2005 version at the moment I cannot test it.

@potatoqualitee - Should I try to get it work for version 2005 or is it out of scope?

**Comment by tonyfountain** [comment]
I have plenty of SQL versions available.  I don't mind doing this either.  For the time being I made my own script that uses this cmdlet, or installs the 2005 versions to support a current client - @andreasjordan  / @potatoqualitee.

**Comment by tonyfountain** [comment]
Also, to add, I would like to also install the SqlServerVersions table to sp_Blitz can benefit from that object.  Only for SQL Server 2008 and above though, since that is all they list in the table.

**Comment by andreasjordan** [comment]
Hi @tonyfountain : 

> Also, to add, I would like to also install the SqlServerVersions table to sp_Blitz can benefit from that object. Only for SQL Server 2008 and above though, since that is all they list in the table.

Hi @tonyfountain : That is possible now and even part of the normal installation.

I will close this for now, but you can reopen it if you have further questions.
