### ISSUE TITLE
Install-DbaFirstResponderKit not working. 404 on download page.

### ISSUE THREAD

**Issue by pontuskindh** [sqlcollaborative/dbatools#6935]
### Report
Install-DbaFirstResponderKit not working. 404 on download page.

#### Host used

- [ ] powershell.exe
- [X] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server re
                        turned an error: (404) Not Found.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], Exception
FullyQualifiedErrorId : dbatools_Install-DbaFirstResponderKit
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.111\allcommands.ps1: line 82978
                        at Install-DbaFirstResponderKit<Begin>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.111\allcommands.ps1: line 
                        39693
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce
```
Install-DbaFirstResponderKit -SqlInstance server1
```
#### Expected Behavior

FirstResponderkit being installed. 

#### Actual Behavior
```
WARNING: [07:55:41][Install-DbaFirstResponderKit] Couldn't download the First Responder Kit. Download and install manually from https://github.com/
BrentOzarULTD/SQL-Server-First-Responder-Kit/archive/master.zip. | The remote server returned an error: (404) Not Found.
```
```
The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.111\allcommands.ps1:82978 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], Exception
    + FullyQualifiedErrorId : dbatools_Install-DbaFirstResponderKit
```

**Comment by tonyfountain** [comment]
@pontuskindh I would suggest installing the latest version of DBATools and see if this still happens.

**Comment by potatoqualitee** [comment]
Agreed. Please update to the latest version, the change in branch name has already been addressed.

**Comment by pontuskindh** [comment]
> @pontuskindh I would suggest installing the latest version of DBATools and see if this still happens. Otherwise, check to see if you're on a computer that is not internet accessible, or firewall blocked.

Yeah i was on an old version. Thanks!
