### ISSUE TITLE
[Bug] Test-DbaConnection does not use -SqlCredential for TcpPort

### ISSUE THREAD

**Issue by mattbob-brock** [sqlcollaborative/dbatools#6971]
### Report

When calling Test-DbaConnection and passing a -SqlCredential where the current user does not have database access 
Eg: `Test-DbaConnection -SqlInstance $SqlInstance -Sqlcredential $Credential -EnableException`

the TcpPort field value is: Login failed for user 'Domain\User'.

It is not a permissions issue as calling these other two methods work:
```
$(Get-DbaTcpPort -SqlCredential $Credential -SqlInstance $SqlInstance).Port
$(Connect-DbaInstance -SqlInstance dwmssql120 -SqlCredential $Credential).NetPort
```
#### Host used

powershell.exe

#### Errors Received

```
PSMessageDetails      :
Exception             : System.Exception: Login failed for user 'DOMAIN\USER'. ---> System.Data.SqlClient.SqlException: Login failed for user 'DOMAIN\USER'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean
                        redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&
                        connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : TCP:TARGETSQLSERVER
CategoryInfo          : ConnectionError: (TCP:TARGETSQLSERVER:String) [], Exception
FullyQualifiedErrorId : dbatools_Get-DbaTcpPort
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\1.0.130\allcommands.ps1: line 85569
                        at Get-DbaTcpPort<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\1.0.130\allcommands.ps1: line 35999
                        at Test-DbaConnection<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\1.0.130\allcommands.ps1: line 71342
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce

1. Create a sql credential on the database instance
2. Login with an account that does not have access to a database.  
2. Run the following:

```powershell
$Credential = Get-Credential
$SqlInstance = "TARGET INSTANCE"
Test-DbaConnection -SqlInstance $SqlInstance -Sqlcredential $Credential
```

#### Expected Behavior

TcpPort contains the port of the instance

#### Actual Behavior

TcpPort contains an error

### Environmental information

```
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-Package : No match was found for the specified search criteria and module names 'dbatools'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2216 char:9
+         PackageManagement\Get-Package @PSBoundParameters | Microsoft. ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
```

```
PowerShell Version        : 5.1.14393.3866
dbatools latest installed :
Culture of OS             : en-US
```

#### SQL Server:
```
Microsoft SQL Server 2017 (RTM-CU22) (KB4577467) - 14.0.3356.20 (X64)   Aug 20 2020 22:33:27   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

us_english
```

**Comment by mattbob-brock** [comment]
I am using dbatools v1.0.130

**Comment by andreasjordan** [comment]
Test-DbaConnection executes Get-DbaTcpPort a bit differently. Can you test this? 
```
$Credential = Get-Credential
$SqlInstance = "TARGET INSTANCE"
$server = Connect-DbaInstance -SqlInstance $SqlInstance -Sqlcredential $Credential
$tcpport = (Get-DbaTcpPort -SqlInstance $server -Credential $Credential -EnableException).Port
```

**Comment by mattbob-brock** [comment]
Yes, these work fine.   I am using this method instead, just reporting that Test-DbaConnection doesnt quite work how I expected.

**Comment by andreasjordan** [comment]
Ok, to understand the situation: The target instance is on a seperate maschine from the one you run dbatools? The $Credential is a domain user that has admin access on the target maschine and on the target instance?

**Comment by andreasjordan** [comment]
Can you try:
```
Test-DbaConnection -SqlInstance $SqlInstance -Sqlcredential $Credential -Credential $Credential
```
Because only -Credential is passed to Get-DbaTcpPort.

**Comment by wsmelton** [comment]
Add of the `-Credential` parameter (ref: PR #6024) was added due to a similar error you are receiving @mattbob-brock. `Get-DbaTcpPort` utilizes remote registry calls to gather the exact port settings. Due to that, the `SqlCredential` is only being used to connect to the SQL Server instance itself, whereas the `Credential` will allow the command to connect to Windows directly and pull the port information.

A PR has been submitted to clear up the documentation a bit around this and provide a detailed example for this use case.

If your credential you are using has rights to login to SQL Server and the Windows Server itself you would simply pass that to both parameters as @andreasjordan pointed out.
