### ISSUE TITLE
Set-DBALogin error on Azure SQL Database

### ISSUE THREAD

**Issue by GeorgePalacios** [sqlcollaborative/dbatools#7004]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      :
Exception             : System.Management.Automation.ExtendedTypeSystemException: The following exception occurred while trying to enumerate the collection: "Operation not supported on version 12.0.2000 SqlAzureDatabase.".
                         ---> Microsoft.SqlServer.Management.Sdk.Sfc.InvalidVersionEnumeratorException: Operation not supported on version 12.0.2000 SqlAzureDatabase.
                           at Microsoft.SqlServer.Management.Smo.XmlReadDoc.LoadInternal()
                           at Microsoft.SqlServer.Management.Smo.SqlObject.LoadInitDataFromAssemblyInternal(Assembly assemblyObject, String file, ServerVersion ver, String alias, StringCollection requestedFields, Boolean
                        store, StringCollection roAfterCreation, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition, Stream configXml)
                           at Microsoft.SqlServer.Management.Smo.SqlObject.LoadInitDataFromAssembly(Assembly assemblyObject, String file, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition
                        databaseEngineEdition)
                           at Microsoft.SqlServer.Management.Smo.SqlObject.LoadInitData(String file, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectCache.LoadElement(ObjectLoadInfo oli, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectCache.GetElement(ObjectLoadInfo oli, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectCache.GetAllElements(Urn urn, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition, Object ci)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetObjectsFromCache(Urn urn, Object ci)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
                           at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
                           at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
                           at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
                           at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp)
                           at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.GetEnumerator(ScriptingPreferences sp)
                           at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.GetEnumerator()
                           at System.Management.Automation.EnumerableOps.GetEnumerator(IEnumerable enumerable)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.EnumerableOps.GetEnumerator(IEnumerable enumerable)
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
FullyQualifiedErrorId : ExceptionInGetEnumerator
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaServerRoleMember<Process>, C:\Users\burcha\Documents\PowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 34732
                        at Set-DbaLogin<Process>, C:\Users\burcha\Documents\PowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 67312
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

```
$login = Get-DbaLogin -SqlInstance $SqlInstance -Login "LoginName"
$login | Set-DbaLogin -SecurePassword $SecurePassword
```

#### Expected Behavior

Password changed to new value - no errors raised

#### Actual Behavior

Password changed to new value, error raised as above

### Environmental information

```

PowerShell Version        : 7.0.3
dbatools latest installed : 1.0.133
Culture of OS             : en-GB

```

#### SQL Server:

```sql
Microsoft SQL Azure (RTM) - 12.0.2000.8
    Oct  1 2020 18:48:35
    Copyright (C) 2019 Microsoft Corporation
```

```sql
us_english
```

**Comment by wsmelton** [comment]
SMO does not support managing SQL Logins. The command needs to exclude this version by having the `-AzureUnsupported` added to the `Connect-SqlInstance` call.

**Comment by GeorgePalacios** [comment]
I'm happy to look to fix this in that case.

This explains the extremely inconsistent behaviour when running against Azure, which oddly doesn't always fail.

**Comment by wsmelton** [comment]
There may be a few things in SMO that work just out of pure luck.
