### ISSUE TITLE
[Bug] Copy-DbaDbTableData appears to ignore passed-in credentials

### ISSUE THREAD

**Issue by MCTSQL** [sqlcollaborative/dbatools#7061]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [x] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'domain\user'. ---> 
                        System.Data.SqlClient.SqlException: Login failed for user 'domain\user'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity 
                        identity, SqlConnectionString connectionOptions, SqlCredential credential, Object 
                        providerInfo, String newPassword, SecureString newSecurePassword, Boolean 
                        redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData 
                        reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean 
                        applyTransientFaultHandling, SqlAuthenticationProviderManager 
                        sqlAuthProviderManager)
                           at 
                        System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions 
                        options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, 
                        DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions 
                        userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnecti
                        onPool pool, DbConnection owningObject, DbConnectionOptions options, 
                        DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection 
                        owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection 
                        owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection 
                        owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean 
                        onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& 
                        connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection 
                        owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection 
                        owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConn
                        ection outerConnection, DbConnectionFactory connectionFactory, 
                        TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : TargetServer
CategoryInfo          : ConnectionError: (hc-dwsql1dev:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaDbTableData,Stop-Function
ErrorDetails          : Login failed for user 'domain\user'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, 
                        C:\Users\user\Documents\WindowsPowerShell\Modules\dbatools\1.0.131\allcommands.ps1: 
                        line 85842
                        at Copy-DbaDbTableData<Process>, 
                        C:\Users\user\Documents\WindowsPowerShell\Modules\dbatools\1.0.131\allcommands.ps1: 
                        line 7544
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce

#1. open powershell.exe or VS Code terminal with normal user credentials 'domain\user'
#2. get admin credentials
$Admin=Get-Credential #domain\user-sa
#3. use admin credentials in call to Copy-DbaDbTableData
Copy-DbaDbTableData -SqlCredential $Admin -SqlInstance SourceServer -Destination TargetServer -Database MyDb -Table dbo.MyTable

#### Expected Behavior

#4. expected the passed-in admin credentials to be used by CopyDbaDbTableData

#### Actual Behavior
#4. unexpectedly receive warning that login failed for the non-passed-in credentials of the non-admin 'domain\user' that started the powershell session

WARNING: [Copy-DbaDbTableData] Error occurred while establishing connection to  | Login failed for user 'domain\user'.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.17763.1490
dbatools latest installed : 1.0.131
Culture of OS             : en-US

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64) 
	Mar 14 2020 16:10:35 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )
```

```sql
us_english
```

**Comment by niphlod** [comment]
j2mc: is the problem here that domain\user has not access to the dest ?

**Comment by wsmelton** [comment]
You will need to provide a credential for your destination server, your repo steps do not show one was provided. If the desire is to use the admin credential for both it would have to be called as such:

```powershell
Copy-DbaDbTableData -SqlCredential $Admin -SqlInstance SourceServer -Destination TargetServer -DestinationSqlCredential $Admin -Database MyDb -Table dbo.MyTable
```

**Comment by wsmelton** [comment]
I do see the error is wrong and we have the wrong variable referenced.

https://github.com/sqlcollaborative/dbatools/blob/51abc180f1d4fb0f9de475e2274aab43f9e03cb4/functions/Copy-DbaDbTableData.ps1#L354-L359

This should have `$Destination` instead of `$instance`. The reason why the warning message is missing the instance name:

> WARNING: [Copy-DbaDbTableData] Error occurred while establishing connection to | Login failed for user 'domain\user'.

**Comment by niphlod** [comment]
Yup, spotted another One on the online docs. Both credential param have the
same description (prolly a cutAndPaste)

Il mer 30 dic 2020, 19:01 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by wsmelton** [comment]
@niphlod you can update the branch I have on the PR if you'd like.
