### ISSUE TITLE
[Bug] Repair-DBAOrphanUser with RemoveNotExisting returns error on Windows Logins

### ISSUE THREAD

**Issue by gpollokoff** [sqlcollaborative/dbatools#7129]
#### Host used

- [X ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Incorrect syntax near '\'. ---> System.Data.SqlClient.SqlException: Incorrect syntax near '\'.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : [EDW_NSAD_DM]
CategoryInfo          : NotSpecified: ([EDW_NSAD_DM]:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Remove-DbaDbOrphanUser,Stop-Function
ErrorDetails          : Incorrect syntax near '\'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 86001
                        at Remove-DbaDbOrphanUser<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 59753
                        at Repair-DbaDbOrphanUser<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.133\allcommands.ps1: line 61838
                        at <ScriptBlock>, C:\DBA\PowershellScripts\debug.ps1: line 1
PipelineIterationInfo : {0, 1}


```

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.133
Culture of OS             : en-US

#### SQL Server:

```sql
Microsoft SQL Server 2012 (SP4-GDR) (KB4583465) - 11.0.7507.2 (X64) 
	Nov  1 2020 00:48:37 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

```

```sql
us_english
```

**Comment by gpollokoff** [comment]
duplicate
