### ISSUE TITLE
[Bug] Get-DbaKbUpdate not working

### ISSUE THREAD

**Issue by krokofant** [sqlcollaborative/dbatools#7204]
#### Host used

- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)
- [x] PowerShell 7

#### Errors Received

```
@{PSMessageDetails=; Exception=System.Exception: You cannot call a method on a null-valued expression.
 ---> System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---; TargetObject=; CategoryInfo=InvalidOperation: (:) [Write-Error], Exception; FullyQualifiedErrorId=dbatools_Get-DbaKbUpdate,Stop-Function; ErrorDetails=You cannot call a method on a null-valued expression.; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Stop-Function, C:\Users\krokofant\Documents\PowerShell\Modules\dbatools\1.0.124\allcommands.ps1: line 84621
at Get-DbaKbUpdate<Process>, C:\Users\krokofant\Documents\PowerShell\Modules\dbatools\1.0.124\allcommands.ps1: line 29422
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
```

#### Steps to Reproduce
```powershell
Get-DbaKbUpdate -Name KB4577194 -Verbose
```

#### Expected Behavior
To get the URL to the update

#### Actual Behavior
No url received. The url query looks broken `?updateid=downloadInformation[i].updateID`
```
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4577194 with 0-byte payload
VERBOSE: received 43414-byte response of content type text/html                                                         VERBOSE: [10:05:44][Get-DbaKbUpdate] 1b006ac2-a397-420b-b4d9-d6b13f053a52                                               VERBOSE: [10:05:44][Get-DbaKbUpdate] Downloading information for 1b006ac2-a397-420b-b4d9-d6b13f053a52                   VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with 159-byte payload                         VERBOSE: received 30253-byte response of content type text/html
VERBOSE: GET https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=downloadInformation[i].updateID with 0-byte payload
VERBOSE: received 3576-byte response of content type text/html
WARNING: [10:05:47][Get-DbaKbUpdate] Failure | You cannot call a method on a null-valued expression.
```

### Environmental information
PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.124
Culture of OS             : en-SE

**Comment by krokofant** [comment]
Same results on 1.0.141

**Comment by krokofant** [comment]
Seems to work if the POST search url is changed to https:
`http://www.catalog.update.microsoft.com/DownloadDialog.aspx` to `https://www.catalog.update.microsoft.com/DownloadDialog.aspx`

@wsmelton Could you review this change? 😊

**Comment by SQL-Dude** [comment]
changing line 144 to https  doesn't seem to work for me.  I still get the same error.

**Comment by krokofant** [comment]
@SQL-Dude If you edited it locally, did you edit the `allcommands.ps1` file or the source file? When installed the command is loaded from the compiled `allcommands.ps1` file.
