### ISSUE TITLE
[Bug] Write-DbaDbTableData doesn't work with temp tables

### ISSUE THREAD

**Issue by awickham10** [sqlcollaborative/dbatools#7459]
#### Host used
- [ ] powershell.exe
- [ ] ISE
- [ ] VS Code
- [x] Other (please specify) - pwsh.exe

#### Errors Received
```
PSMessageDetails      :
Exception             : System.Exception: Invalid object name '#Processes'.
                        Database name 'DBA' ignored, referencing object in tempdb.
                        Database name 'DBA' ignored, referencing object in tempdb.
                         ---> System.Data.SqlClient.SqlException (0x80131904): Invalid object name '#Processes'.
                        Database name 'DBA' ignored, referencing object in tempdb.
                        Database name 'DBA' ignored, referencing object in tempdb.
                           at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
                           at System.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
                           at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
                        ClientConnectionId:40072e28-a8c5-4725-8064-51e5b7083599
                        Error Number:208,State:0,Class:16
                           --- End of inner exception stack trace ---
TargetObject          : REMOVED
CategoryInfo          : NotSpecified: (REMOVED:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Invalid object name '#Processes'.
                        Database name 'DBA' ignored, referencing object in tempdb.
                        Database name 'DBA' ignored, referencing object in tempdb.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\REMOVED\Documents\PowerShell\Modules\dbatools\1.0.155\allcommands.ps1: line 89752
                        at Write-DbaDbTableData<End>, C:\Users\REMOVED\Documents\PowerShell\Modules\dbatools\1.0.155\allcommands.ps1: line 81161
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce
```
$smo = connect-dbainstance -sqlinstance $server -NonPooledConnection
$processes = get-process
$processes | select Id, ProcessName | Write-DbaDataTable -SqlInstance $smo -Database 'DBA' -Table '#Processes' -AutoCreateTable
```

#### Expected Behavior
Create a temporary table with two columns (Id, ProcessName) and data from `$processes`.

#### Actual Behavior
Temporary table is created but data is not loaded due to the bulk copy coming in on a different session (so temporary table doesn't exist for that session).

### Environmental information
```
PowerShell Version        : 7.1.3
dbatools latest installed : 1.0.155
Culture of OS             : en-US
```

#### SQL Server:
```
Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64)   Nov  6 2020 18:19:52   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

```
us_english
```

**Comment by andreasjordan** [comment]
After reading #7009 again I think this will be solvable, but it will not be easy.
It is a lot related to how we open the connection with Connect-DbaInstance.
So I would like to work on this after the new code path in Connect-DbaInstance is the default one.

**Comment by potatoqualitee** [comment]
yeah, this one is going to be rough. 

![image](https://user-images.githubusercontent.com/8278033/123160345-5a375980-d46e-11eb-8db9-d79954ab3b6e.png)
