### ISSUE TITLE
Connect-DbaInstance, Failed to generate SSPI Context

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#7545]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
PSMessageDetails      : 
Exception             : System.Exception: Failed to generate SSPI context.
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to generate SSPI context.
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIError(String error, String procedure)
                           at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.ProcessSSPI(Int32 receivedLength)
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:af65d175-bdf3-4834-8ae9-ae5360181e06
                           --- End of inner exception stack trace ---
TargetObject          : localhost
CategoryInfo          : ConnectionError: (localhost:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaDatabase,Stop-Function
ErrorDetails          : Failed to generate SSPI context.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\github\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 229
                        at Get-DbaDatabase<Process>, C:\github\dbatools\functions\Get-DbaDatabase.ps1: line 191
                        at Get-DbaDbFile<Process>, C:\github\dbatools\functions\Get-DbaDbFile.ps1: line 152
                        at Invoke-DbaBalanceDataFiles<Process>, C:\github\dbatools\functions\Invoke-DbaBalanceDataFiles.ps1: line 220
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

PSMessageDetails      : 
Exception             : System.Exception: Failed to generate SSPI context.
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to generate SSPI context.
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIError(String error, String procedure)
                           at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.ProcessSSPI(Int32 receivedLength)
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:af65d175-bdf3-4834-8ae9-ae5360181e06
                           --- End of inner exception stack trace ---
TargetObject          : localhost
CategoryInfo          : ConnectionError: (localhost:String) [], Exception
FullyQualifiedErrorId : dbatools_Connect-DbaInstance
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\github\dbatools\internal\functions\flowcontrol\Stop-Function.ps1: line 221
                        at Connect-DbaInstance<Process>, C:\github\dbatools\functions\Connect-DbaInstance.ps1: line 891
                        at Connect-SqlInstance, C:\github\dbatools\internal\functions\Connect-SqlInstance.ps1: line 74
                        at Get-DbaDatabase<Process>, C:\github\dbatools\functions\Get-DbaDatabase.ps1: line 189
                        at Get-DbaDbFile<Process>, C:\github\dbatools\functions\Get-DbaDbFile.ps1: line 152
                        at Invoke-DbaBalanceDataFiles<Process>, C:\github\dbatools\functions\Invoke-DbaBalanceDataFiles.ps1: line 220
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" with "1" argument(s): "Failed to connect to server localhost."
                         ---> Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server localhost.
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to generate SSPI context.
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIError(String error, String procedure)
                           at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
                           at Microsoft.Data.SqlClient.TdsParser.ProcessSSPI(Int32 receivedLength)
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                        ClientConnectionId:af65d175-bdf3-4834-8ae9-ae5360181e06
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect()
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                           at CallSite.Target(Closure , CallSite , Object , String )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ConnectionFailureException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-DbaInstance<Process>, C:\github\dbatools\functions\Connect-DbaInstance.ps1: line 889
                        at Connect-SqlInstance, C:\github\dbatools\internal\functions\Connect-SqlInstance.ps1: line 74
                        at Get-DbaDatabase<Process>, C:\github\dbatools\functions\Get-DbaDatabase.ps1: line 189
                        at Get-DbaDbFile<Process>, C:\github\dbatools\functions\Get-DbaDbFile.ps1: line 152
                        at Invoke-DbaBalanceDataFiles<Process>, C:\github\dbatools\functions\Invoke-DbaBalanceDataFiles.ps1: line 220
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Steps to Reproduce

Setup the docker containers from dbatools.io/docker, then execute the following in PowerShell Core
```powershell
Invoke-DbaBalanceDataFiles -SqlInstance localhost -Database Northwind -Force
```

### Are you running the latest release?

Yes

### Other details or mentions

This was also broken with the old code path *AND* the old SMO

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0                                           
```

### SQL Server Edition and Build number

dbatools.io/docker

**Comment by andreasjordan** [comment]
Ok, I need to setup docker for this - will take some time...

Googleing leads to this most times: https://support.microsoft.com/en-us/topic/how-to-troubleshoot-the-cannot-generate-sspi-context-error-message-03d15ff2-e062-e023-272c-d5cd413c37b3

I'm not the Kerberos expert...

**Comment by potatoqualitee** [comment]
Kerberos only comes into play when Windows Auth is used -- in this case, SQL Auth was used. So the issue will be with SMO or SqlClient 🤔

**Comment by potatoqualitee** [comment]
Ohh, the debug was super helpful! 

```
DEBUG: 111 | [14:59:28][Invoke-DbaBalanceDataFiles] Starting balancing out data files
DEBUG: 444 | [14:59:28][Connect-DbaInstance] Starting process block
DEBUG: 446 | [14:59:28][Connect-DbaInstance] Starting loop for 'localhost': ComputerName = 'localhost', InstanceName = 'MSSQLSERVER', IsLocalHost = 'True', Type = 'Default'
DEBUG: 557 | [14:59:28][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: 340 | [14:59:28][Test-Azure] Test for Azure is negative
DEBUG: 660 | [14:59:28][Connect-DbaInstance] authentication method is 'local sql'
DEBUG: 695 | [14:59:28][Connect-DbaInstance] ApplicationName will be set to 'dbatools PowerShell module - dbatools.io'
DEBUG: 727 | [14:59:28][Connect-DbaInstance] ConnectionTimeout will be set to '15'
DEBUG: 757 | [14:59:28][Connect-DbaInstance] PacketSize will be set to '4096'
DEBUG: 776 | [14:59:28][Connect-DbaInstance] Pooled will be set to 'True'
DEBUG: 785 | [14:59:28][Connect-DbaInstance] SecurePassword will be set
DEBUG: 811 | [14:59:28][Connect-DbaInstance] UserName will be set to 'sqladmin'
DEBUG: 835 | [14:59:28][Connect-DbaInstance] Building ServerConnection from SqlConnectionInfo
DEBUG: 837 | [14:59:28][Connect-DbaInstance] ServerConnection was build
DEBUG: 851 | [14:59:28][Connect-DbaInstance] Building Server from ServerConnection
DEBUG: 853 | [14:59:28][Connect-DbaInstance] Server was build
DEBUG: 872 | [14:59:28][Connect-DbaInstance] Setting ConnectionContext.StatementTimeout to '0'
DEBUG: 877 | [14:59:28][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=localhost;User ID=sqladmin;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: 887 | [14:59:28][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: 893 | [14:59:28][Connect-DbaInstance] We have a connected server object
DEBUG: 935 | [14:59:28][Connect-DbaInstance] We are on Linux what is often on docker and the internal name is not useful, so server.ComputerName will be set to instance.ComputerName
DEBUG: 944 | [14:59:28][Connect-DbaInstance] ComputerName will be set to localhost
DEBUG: 340 | [14:59:28][Test-Azure] Test for Azure is negative
DEBUG: 954 | [14:59:28][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'MSSQLSERVER', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '1433', ConnectedAs = server.ConnectionContext.TrueLogin = 'sqladmin'
DEBUG: 957 | [14:59:28][Connect-DbaInstance] We return the server object
DEBUG: 985 | [14:59:28][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: 1009 | [14:59:28][Connect-DbaInstance] We are finished with this instance
DEBUG: 158 | [14:59:29][Get-DbaDbFile] Querying database [Northwind]
DEBUG: 175 | [14:59:29][Get-DbaDbFile] SQL Statement: select
            fg.name as FileGroupName,
            df.file_id as 'ID',
            df.Type,
            df.type_desc as TypeDescription,
            df.name as LogicalName,
            mf.physical_name as PhysicalName,
            df.state_desc as State,
            df.max_size as MaxSize,
            case mf.is_percent_growth when 1 then df.growth else df.Growth*8 end as Growth,
            COALESCE(fileproperty(df.name, 'spaceused'), 0) as UsedSpace,
            df.size as Size,
            COALESCE(vfs.size_on_disk_bytes, 0) as size_on_disk_bytes,
            case df.state_desc when 'OFFLINE' then 'True' else 'False' End as IsOffline,
            case mf.is_read_only when 1 then 'True' when 0 then 'False' End as IsReadOnly,
            case mf.is_media_read_only when 1 then 'True' when 0 then 'False' End as IsReadOnlyMedia,
            case mf.is_sparse when 1 then 'True' when 0 then 'False' End as IsSparse,
            case mf.is_percent_growth when 1 then 'Percent' when 0 then 'kb' End as GrowthType,
            COALESCE(vfs.num_of_writes, 0) as NumberOfDiskWrites,
            COALESCE(vfs.num_of_reads, 0) as NumberOfDiskReads,
            COALESCE(vfs.num_of_bytes_read, 0) as BytesReadFromDisk,
            COALESCE(vfs.num_of_bytes_written, 0) as BytesWrittenToDisk,
            fg.data_space_id as FileGroupDataSpaceId,
            fg.Type as FileGroupType,
            fg.type_desc as FileGroupTypeDescription,
            case fg.is_default When 1 then 'True' when 0 then 'False' end as FileGroupDefault,
            fg.is_read_only as FileGroupReadOnly
,vs.available_bytes as 'VolumeFreeSpace'
from sys.database_files df
            left outer join  sys.filegroups fg on df.data_space_id=fg.data_space_id
            left join sys.dm_io_virtual_file_stats(db_id(),NULL) vfs on df.file_id=vfs.file_id
            inner join sys.master_files mf on df.file_id = mf.file_id
            and mf.database_id = db_id()
cross apply sys.dm_os_volume_stats(db_id(),df.file_id) vs
DEBUG: 216 | [14:59:29][Invoke-DbaBalanceDataFiles] Retrieving data files before data move
DEBUG: 217 | [14:59:29][Invoke-DbaBalanceDataFiles] Processing database [Northwind]
DEBUG: 444 | [14:59:29][Connect-DbaInstance] Starting process block
DEBUG: 446 | [14:59:29][Connect-DbaInstance] Starting loop for 'localhost': ComputerName = 'localhost', InstanceName = 'MSSQLSERVER', IsLocalHost = 'True', Type = 'Default'
DEBUG: 557 | [14:59:29][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: 340 | [14:59:29][Test-Azure] Test for Azure is negative
DEBUG: 660 | [14:59:29][Connect-DbaInstance] authentication method is 'local integrated'
DEBUG: 695 | [14:59:29][Connect-DbaInstance] ApplicationName will be set to 'dbatools PowerShell module - dbatools.io'
DEBUG: 727 | [14:59:29][Connect-DbaInstance] ConnectionTimeout will be set to '15'
DEBUG: 757 | [14:59:29][Connect-DbaInstance] PacketSize will be set to '4096'
DEBUG: 776 | [14:59:29][Connect-DbaInstance] Pooled will be set to 'True'
DEBUG: 835 | [14:59:29][Connect-DbaInstance] Building ServerConnection from SqlConnectionInfo
DEBUG: 837 | [14:59:29][Connect-DbaInstance] ServerConnection was build
DEBUG: 851 | [14:59:29][Connect-DbaInstance] Building Server from ServerConnection
DEBUG: 853 | [14:59:29][Connect-DbaInstance] Server was build
DEBUG: 872 | [14:59:29][Connect-DbaInstance] Setting ConnectionContext.StatementTimeout to '0'
DEBUG: 877 | [14:59:29][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=localhost;Integrated Security=True;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: 887 | [14:59:29][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:59:29][Connect-DbaInstance] Failure | Failed to generate SSPI context.
```

The connstring changes from username and pass to integrated security

**Comment by potatoqualitee** [comment]
YAY, this is an issue with another command, brb

**Comment by potatoqualitee** [comment]
This was a problem with the calling command, not `Connect-DbaInstance` 👍🏼 Will fix in a new PR
