### ISSUE TITLE
Running New-DbaDbSnapshot with an sa account from a linux container on wsl2 against a SQL Server 2019 Express instance on the host runs into a file activation error

### ISSUE THREAD

**Issue by QuadmanSWE** [sqlcollaborative/dbatools#7651]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Exception: Error connecting to [host.docker.internal]: A file activation error occurred. The physical file name 'C:/Program Files/Microsoft SQL Server/MSSQL15.SQLEXPRESS/MSSQL/DATA/C:\Program Files\Microsoft SQL Server\MSSQL15.ss' may be incorrect. Diagnose and correct additional errors, and retry the operation.
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): A file activation error occurred. The physical file name 'C:/Program Files/Microsoft SQL Server/MSSQL15.SQLEXPRESS/MSSQL/DATA/C:\Program Files\Microsoft SQL Server\MSSQL15.ss' may be incorrect. Diagnose and correct additional errors, and retry the operation.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlCommand, Boolean retry)
                        ClientConnectionId:432a444a-a319-4222-8374-3e678136b6f8
                        Error Number:5105,State:2,Class:16
                           --- End of inner exception stack trace ---
TargetObject          : [tes_docker_snapshot]
CategoryInfo          : NotSpecified: ([tes_docker_snapshot]:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_New-DbaDbSnapshot,Stop-Function
ErrorDetails          : Error connecting to [host.docker.internal]: A file activation error occurred. The physical file name 'C:/Program Files/Microsoft SQL Server/MSSQL15.SQLEXPRESS/MSSQL/DATA/C:\Program Files\Microsoft SQL Server\MSSQL15.ss' may be incorrect. Diagnose and correct additional errors, and retry the operation.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, /root/.local/share/powershell/Modules/dbatools/1.1.3/allcommands.ps1: line 90897
                        at New-DbaDbSnapshot<Process>, /root/.local/share/powershell/Modules/dbatools/1.1.3/allcommands.ps1: line 56764
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

```powershell
#having the environment variables for the instance, database, sqluser and password set in the container already

$splat = @{
    SqlInstance   = $env:DB_SERVICENAME
    Database      = $env:TES_DB
    SqlCredential = (New-Object PSCredential $env:SA_USER, ($env:SA_PASSWORD| ConvertTo-SecureString -AsPlainText -Force))
}

New-DbaDbSnapshot @splat -Name "$(($splat).Database)_snapshot"
```

### Are you running the latest release?

Yes

### Other details or mentions

The code for creating the snapshot works when running with the same sql credentials from the host machine. When entering the container with docker exec -ti <containername> /bin/pwsh and running it I get this error.

I have had success in creating, removing databases and restoring and removing snapshots in this fashion but initializing the snapshot runs into this file activation error.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU11) (KB5003249) - 15.0.4138.2 (X64) 
	May 27 2021 17:34:14 
	Copyright (C) 2019 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19041: ) (Hypervisor)

**Comment by QuadmanSWE** [comment]
If it is of help in debugging, I can publish the docker image I am running the command on to docker hub and give instructions on how to set it up to express running on the host.
