### ISSUE TITLE
Write-DbaDbTableData ignores -SQLCredential

### ISSUE THREAD

**Issue by Fabaderheld** [sqlcollaborative/dbatools#7762]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Exception: Error connecting to [[mssql-impimba-1.imp.univie.ac.at]]: Cannot open database "Database" requested by the login. The login failed.
                        Login failed for user 'domain\myuser'.
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "Database" requested by the login. The login failed.
                        Login failed for user 'domain\myuser'.
                           at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
                           at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
                           at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
                           at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
                           at Microsoft.Data.SqlClient.SqlBulkCopy.CreateOrValidateConnection(String method)
                           at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
                           at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                        ClientConnectionId:7a55189d-e939-43ca-a428-88eab32e2bdf
                        Error Number:4060,State:1,Class:11
                           --- End of inner exception stack trace ---
TargetObject          : mssql-impimba-1.imp.univie.ac.at
CategoryInfo          : NotSpecified: (mssql-impimba-1.imp.univie.ac.at:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Write-DbaDbTableData,Stop-Function
ErrorDetails          : Error connecting to [[mssql-impimba-1.imp.univie.ac.at]]: Cannot open database "Database" requested by the login. The login failed.
                        Login failed for user 'domain\myuser'.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\fabian.sasse\Documents\PowerShell\Modules\dbatools\1.1.15\allcommands.ps1: line 91340
                        at Write-DbaDbTableData<End>, C:\Users\fabian.sasse\Documents\PowerShell\Modules\dbatools\1.1.15\allcommands.ps1: line 82628
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
$SQLDataBase = "Database"
$SQLTable = "Inventory"
$SQLServer = "mssql.xxxx.ac.at"
$SQLCredential = Get-Credential domain\adminuser

$TableData = Import-Csv $CSVPath -Delimiter ";"

$Instance = Connect-DbaInstance -SqlInstance $SQLServer -SqlCredential $SQLCredential -Database $SQLDataBase

$Instance.ConnectedAs
domain\adminuser

Write-DbaDbTableData -SqlInstance $Instance -Database $SQLDataBase -InputObject $TableData -AutoCreateTable -Table $SQLTable -SqlCredential $SQLCredential -Verbose

VERBOSE: [11:49:02][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:49:02][Write-DbaDbTableData] FQTN processed: [Database].[dbo].[Inventory]
VERBOSE: [11:49:02][Write-DbaDbTableData] Creating SqlBulkCopy object
VERBOSE: [11:49:02][Invoke-BulkCopy] Importing in bulk to [Database].[dbo].[Inventory]
WARNING: [11:49:12][Write-DbaDbTableData] Failed to bulk import to [Database].[dbo].[Inventory] | Error connecting to [[mssql.xxxx.ac.at]]: Cannot open database "Database" requested by the login. The login failed.
Login failed for user 'domain\myuser'.
VERBOSE: [11:49:12][Disconnect-DbaInstance] removing from connection hash

# please include variable values (redacted or fake if needed) for reference
```

### Are you running the latest release?

Yes

### Other details or mentions

`Write-DbaDbTableData` should be executed as `domain\adminuser` instead is run as `domain\myuser` who is running the pwsh. 
It is behaving correctly 
`Invoke-DbaQuery -SqlInstance $Instance -Database $SQLDataBase -Query "SELECT TOP 1000 [HostName] FROM [Database].[dbo].[Inventory]"`

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

````
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-GDR) (KB4583460) - 13.0.5103.6 (X64) 
	Nov  1 2020 00:13:28 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by andreasjordan** [comment]
Could you please add `-NonPooledConnection` to `$Instance = Connect-DbaInstance -SqlInstance $SQLServer -SqlCredential $SQLCredential -Database $SQLDataBase`? That might be a quick fix for that. Will try to find time to have a closer look later.

**Comment by Fabaderheld** [comment]
Sorry I tried it already doesn't help either.

**Comment by andreasjordan** [comment]
And I think I mixed two issues - sorry for that.

**Comment by andreasjordan** [comment]
Does it work if you use `-SqlInstance $SQLServer -SqlCredential $SQLCredential` with `Write-DbaDbTableData` and do not use `Connect-DbaInstance` yourself?

**Comment by andreasjordan** [comment]
In your verbose output, this line is missing:
```
VERBOSE: [12:55:00][Connect-DbaInstance] NonPooledConnection provided. Does not match ConnectionContext.NonPooledConnection, copying ConnectionContext and setting NonPooledConnection 
```

So are your sure to be on the latest version?

**Comment by andreasjordan** [comment]
Sorry for all the small messages...

I think we discussed this earlier - will try to link the issue.

The problem is here:
```
$bulkCopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy($server.ConnectionContext.ConnectionString, $bulkCopyOptions)
```

The different windows user is not part of the ConnectionString - so your use case is just impossible. Use a SQL Server Login or run the PowerShell session under the target windows account.

**Comment by andreasjordan** [comment]
Here is the issue: https://github.com/sqlcollaborative/dbatools/issues/6618

**Comment by andreasjordan** [comment]
I think we should change the documentation to say that this command only works with SQL Logins or integrated security, NOT with a different windows login.

**Comment by Fabaderheld** [comment]
Thanks Andreas, I read through this  issue but was under the impression it should work now with Windows Creds. We will work around this somehow. 
regards
Fabian

**Comment by andreasjordan** [comment]
Hi Fabian,

I wanted to solve that issue as well, but in the end could only solve the issue with the database context. And looking at the code again, I don't see a way to solve this. Using a different windows account while connecting with Connect-DbaInstance uses some magic inside of the SMO library. But every time we use other libraries like Microsoft.Data.SqlClient.SqlBulkCopy here in this command - we have a problem because this context is lost.

Let's see if I'm wrong and others (@potatoqualitee / @niphlod / @wsmelton) have an idea. Otherwise I would open a pull request with a change in the documentation. 

Regards
Andreas

**Comment by andreasjordan** [comment]
Ok, some more time digging in diffs - I think I have implemented a solution in this commit:
https://github.com/sqlcollaborative/dbatools/commit/c5413f8e914e74b6d2287fec9152e62cfd350540#diff-1c01f27614f67c2c9b6e9e242800a40280c9c380d049d4e1057ec31f003498bd

But it got accidently overwritten in some later change. Will open a pull request soon to put it back in.

**Comment by andreasjordan** [comment]
Fabian, maybe you can change that line in your allcommands.ps1 and have a try.

**Comment by andreasjordan** [comment]
Great to hear that! Und viele Grüße nach Österreich...
