### ISSUE TITLE
Backup-DbaDatabase fails on macOS when connecting to a Windows-hosted instance

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#7860]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
@{PSMessageDetails=; Exception=System.Exception: Microsoft.Data.SqlClient.SqlError: Cannot open backup device 'C:\SQL\Backup\Users\andy\code\community-presentations\andy-levy\BackupBasics\satellites\C:\SQL\Backup\satellites_202110132221.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.).
 ---> System.Management.Automation.MethodInvocationException: Exception calling "SqlBackup" with "1" argument(s): "Backup failed for Server 'flexo\sql17'. "
 ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Backup failed for Server 'flexo\sql17'. 
 ---> Microsoft.SqlServer.Management.Smo.SmoException: Microsoft.Data.SqlClient.SqlError: Cannot open backup device 'C:\SQL\Backup\Users\andy\code\community-presentations\andy-levy\BackupBasics\satellites\C:\SQL\Backup\satellites_202110132221.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.).
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries, ServerMessageEventHandler dbccMessageHandler, Boolean errorsAsMessages, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
   at Microsoft.SqlServer.Management.Smo.Backup.SqlBackup(Server srv)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Backup.SqlBackup(Server srv)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---; TargetObject=; CategoryInfo=NotSpecified: (:) [Write-Error], Exception; FullyQualifiedErrorId=dbatools_Backup-DbaDatabase,Stop-Function; ErrorDetails=Microsoft.Data.SqlClient.SqlError: Cannot open backup device 'C:\SQL\Backup\Users\andy\code\community-presentations\andy-levy\BackupBasics\satellites\C:\SQL\Backup\satellites_202110132221.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.).; InvocationInfo=System.Management.Automation.InvocationInfo; ScriptStackTrace=at Stop-Function, /Users/andy/.local/share/powershell/Modules/dbatools/1.1.24/allcommands.ps1: line 91905
at Backup-DbaDatabase<Process>, /Users/andy/.local/share/powershell/Modules/dbatools/1.1.24/allcommands.ps1: line 1917
at <ScriptBlock>, <No file>: line 1; PipelineIterationInfo=System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]}
```

### Steps to Reproduce

```powershell
$Credential = Import-CliXml -Path /Users/andy/code/community-presentations/andy-levy/BackupBasics/Credential.xml;
Connect-DbaInstance -SqlInstance flexo\sql17 -SqlCredential $Credential;
test-dbapath -path C:\SQL\Backup\satellites -SqlCredential $credential -sqlinstance flexo\sql17;
$BackupPath = "C:\SQL\Backup\";
Backup-DbaDatabase -sqlinstance flexo\sql17 -SqlCredential $Credential -CreateFolder -Path $BackupPath -Database satellites -verbose
```

### Are you running the latest release?

Yes

### Other details or mentions

Running pwsh on macOS, attempting to back up a database residing on an instance hosted on Windows. Path specified for the backup is local to the SQL Server instance. Everything works fine when executed on the Windows machine where the instance is hosted.

In talking to @cfradenburg on Slack, we believe it has something to do with this section:

```
 if ($null -eq $AzureBaseUrl -and $Path) {
                $FinalBackupPath = $FinalBackupPath | ForEach-Object { [IO.Path]::GetFullPath($_) }
            }
```

`[IO.Path]::GetFullPath()` doesn't seem to know what to do when it's handed a path formatted for a different OS, so it returns the current working directory concatenated with the string that's passed in, thinking that the string is a relative path.

Full transcript of running the above code:

```
PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> $Credential = Import-CliXml -Path /Users/andy/code/community-presentations/andy-levy/BackupBasics/Credential.xml;
PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> Connect-DbaInstance -SqlInstance flexo\sql17 -SqlCredential $Credential;

ComputerName Name        Product              Version   HostPlatform IsAzure IsClustered ConnectedAs
------------ ----        -------              -------   ------------ ------- ----------- -----------
FLEXO        flexo\sql17 Microsoft SQL Server 14.0.3411 Windows      False   False       andyremote

PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> test-dbapath -path C:\SQL\Backup\satellites -SqlCredential $credential -sqlinstance flexo\sql17;
True
PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> $BackupPath = "C:\SQL\Backup\";
PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> Backup-DbaDatabase -sqlinstance flexo\sql17 -SqlCredential $Credential -CreateFolder -Path $BackupPath -Database satellites -verbose
VERBOSE: [22:21:36][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [22:21:36][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [22:21:36][Connect-DbaInstance] authentication method is 'local sql'
VERBOSE: [22:21:36][Backup-DbaDatabase] 1 database to backup
VERBOSE: [22:21:36][Backup-DbaDatabase] Backup database [satellites]
VERBOSE: [22:21:36][Backup-DbaDatabase] Creating full backup
VERBOSE: [22:21:36][Backup-DbaDatabase] Building file name
VERBOSE: [22:21:36][Backup-DbaDatabase] Setting filename - 202110132221
VERBOSE: [22:21:36][Backup-DbaDatabase] Building backup path
VERBOSE: [22:21:36][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [22:21:36][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [22:21:37][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
WARNING: [22:21:37][New-DbaDirectory] Failure | Error connecting to [FLEXO\sql17]: xp_create_subdir() returned error 123, 'The filename, directory name, or volume label syntax is incorrect.'
VERBOSE: [22:21:37][Backup-DbaDatabase] Devices added
VERBOSE: Performing the operation "Backing up satellites to /Users/andy/code/community-presentations/andy-levy/BackupBasics/satellites/C:\SQL\Backup\\satellites_202110132221.bak" on target "flexo\sql17".
WARNING: [22:21:37][Backup-DbaDatabase] Backup Failed | Microsoft.Data.SqlClient.SqlError: Cannot open backup device 'C:\SQL\Backup\Users\andy\code\community-presentations\andy-levy\BackupBasics\satellites\C:\SQL\Backup\satellites_202110132221.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.).
PS /Users/andy/code/community-presentations/andy-levy/BackupBasics> TerminatingError(): "System error."
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

SQL Server 2017 CU26. 14.0.3411

### .NET Framework Version

.NET 5.0.9

**Comment by andreasjordan** [comment]
`Find-DbaOrphanedFile` also uses `[IO.Path]::GetFullPath` and should be changed as well.

**Comment by andreasjordan** [comment]
I just removed the code and it works "on my machine". But I have a windows only environment. Maybe you can test the changes in your environemnt? Will open a pull request so that you can see the changes.
