### ISSUE TITLE
Invoke-DbaWhoIsActive - Invalid Query For -*FilterType Params With CS Collation

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7881]
### Verified issue does not already exist?

Yes

### What error did you receive?

Basic Powershell Core message is `WARNING: [10:36:43][Invoke-DbaWhoIsActive] Invalid query.`

Full error output.

```powershell

PSMessageDetails      : 
Exception             : System.Exception: Invalid query.
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaWhoIsActive,Stop-Function
ErrorDetails          : Invalid query.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, 
                 C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 91956
                        at Invoke-DbaWhoIsActive<Process>, 
                 C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 50189
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Steps to Reproduce

```powershell
# Install Case Sensitive SQL Server Instance and Run below.
Invoke-DbaWhoIsActive localhost -NotFilter '%dbatools%' -NotFilterType Program
```

### Are you running the latest release?

Yes

#### Additional Error Information

I used a trace to grab the code. Here is a better error message using `Invoke-DbaQuery localhost -Query "exec dbo.sp_WhoIsActive @filter=N'%dbatools%',@filter_type=N'Program'"` from a SQL Instance with a Case Sensitive Collation.

Basic message: `WARNING: [10:39:15][Invoke-DbaQuery] [localhost] Failed during execution | Error connecting to [localhost]: Valid filter types are: session, program, database, login, host`
Full Message:
```powershell
PSMessageDetails      : 
Exception             : System.Exception: Error connecting to [localhost]: Valid filter types are: session, program, database, login, host
                         ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Valid filter types are: session, program, database, login, host
                           at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                           at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
                           at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                           at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                           at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
                           at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
                           at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
                           at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
                           at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
                           at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
                           at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
                           at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                        ClientConnectionId:f9e7c28b-7dd7-4501-bc3f-853882d2a1bf
                        Error Number:50000,State:1,Class:16
                           --- End of inner exception stack trace ---
TargetObject          : localhost
CategoryInfo          : NotSpecified: (localhost:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaQuery,Stop-Function
ErrorDetails          : Error connecting to [localhost]: Valid filter types are: session, program, database, login, host
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 91956
                        at Invoke-DbaQuery<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 49659
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Workaround
Pass the Filter Type as lowercase explicitly. 
`Invoke-DbaWhoIsActive localhost -NotFilter '%dbatools%' -NotFilterType 'program'`

#### Potential Fix
Lowercase the `-NotFilterType` and `-FilterType` after they are pushed in. I guess it could be another `if { }` block within this section of code?

https://github.com/sqlcollaborative/dbatools/blob/865759879900eaeafb16e78c3ec375ea33c42df5/functions/Invoke-DbaWhoIsActive.ps1#L296-L305

##### P.S.
This line stood out because it didn't have an `@` sign. It appears the code still works correctly without it. I think it would be reasonable to add the character in a future PR based on this Issue.
https://github.com/sqlcollaborative/dbatools/blob/865759879900eaeafb16e78c3ec375ea33c42df5/functions/Invoke-DbaWhoIsActive.ps1#L249

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64) 
	Dec 28 2017 15:21:01 
	Copyright (c) 1988-2008 Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (VM)
```
The applicable database setting is Case Sensitivity.

### .NET Framework Version

```powershell
.NET 5.0.11
```

**Comment by mattcargile** [comment]
> The command opens a new connection to the instance. Maybe we should refactor the command and use Invoke-DbaQuery internally. This way we could even have a new parameter "As" to get the result as something else as rows. (But we would have to remove the alias As - why is it there?)

It looks like `As` is an `Alias` for `-Filter`. That seems a bit weird in the context of other cmdlets in dbatools. I like both of your ideas though. It would be nice to have an `-As` similar to `Invoke-DbaQuery`. Not sure how the `SingleValue` input would be handled in this case.

**Comment by andreasjordan** [comment]
Good hint, we should not use the original 
```
        [ValidateSet("DataSet", "DataTable", "DataRow", "PSObject", "PSObjectArray", "SingleValue")]
        [string]$As = "DataRow",
```
but
```
        [ValidateSet("DataSet", "DataTable", "DataRow", "PSObject")]
        [string]$As = "DataRow",
```

**Comment by andreasjordan** [comment]
Just opened a pull request for that. Can you test that, @mattcargile ?
